import test from 'node:test';
import assert from 'node:assert/strict';
import {validateDevice,geometrySample,sampleCurve,direction,toMm,fromMm,emptyLibrary,saveDevice,writeLibrary,readLibrary,parseLibrary,mergeLibrary,advanceClock} from '../launch/device-core.js';
const base={id:'test-cylinder',name:'Test cylinder',lengthMm:200,widthMm:32,travelMm:150,color:'#a080e0',material:'Silicone',texture:'Smooth',shape:'Cylinder',finish:'Matte'};
const storage=()=>{const map=new Map();return {getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v)};};
test('inch/mm round trip',()=>{assert.equal(toMm(2),2);assert.equal(toMm(2,'in'),50.8);assert.equal(fromMm(50.8,'in'),2);});
test('dimensions and color are validated',()=>{assert.throws(()=>validateDevice({...base,travelMm:201}));assert.throws(()=>validateDevice({...base,widthMm:-1}));assert.throws(()=>validateDevice({...base,color:'red;display:none'}));assert.throws(()=>validateDevice({...base,lengthMm:Infinity}));});
test('metadata is allowlisted and unrelated fields discarded',()=>{const d=validateDevice({...base,secret:'no'});assert.ok(!('secret'in d));assert.throws(()=>validateDevice({...base,material:'magic'}));});
test('idle remains at origin even with arbitrary phase',()=>{const s=geometrySample({phase:.4,target:.8,device:base});assert.equal(s.position,0);assert.equal(s.speed,0);});
test('zero target means zero movement and speed',()=>{const s=geometrySample({phase:.3,target:0,running:true,period:4,device:base});assert.equal(s.position,0);assert.equal(s.speed,0);});
test('target travel uses usable length rather than full length',()=>{const s=geometrySample({phase:.5,target:.6,running:true,device:base,period:4});assert.equal(s.targetDistance,90);assert.equal(s.position,90);});
test('active travel cannot exceed target',()=>{for(let i=0;i<300;i++){const s=geometrySample({phase:i/300,target:.7,running:true,device:base,period:4});assert.ok(s.position>=0&&s.position<=s.targetDistance);}});
test('pause holds phase and reports zero speed',()=>{const s=geometrySample({phase:.25,target:.8,started:true,running:false,period:4,device:base});assert.ok(Math.abs(s.position-60)<1e-8);assert.equal(s.speed,0);});
test('speed has distance per second units',()=>{const s=geometrySample({phase:.25,target:1,running:true,period:4,device:base});assert.ok(Math.abs(s.speed-150*Math.PI/4)<1e-7);});
test('30 degree pitch follows the actual path',()=>{const s=geometrySample({phase:.5,target:1,pitch:30,running:true,device:base});assert.ok(Math.abs(s.y/s.x-Math.tan(Math.PI/6))<1e-9);});
test('yaw and pitch unit vector has unit magnitude',()=>{const v=direction(30,40);assert.ok(Math.abs(Math.hypot(v.x,v.y,v.z)-1)<1e-10);});
test('custom paths close at origin and do not overshoot',()=>{const c=[1,-4,2,.5];assert.equal(sampleCurve(0,c).fraction,0);for(let i=0;i<100;i++){const v=sampleCurve(i/100,c).fraction;assert.ok(v>=0&&v<=1);}});
test('invalid imports and duplicate IDs rejected',()=>{assert.throws(()=>parseLibrary('{"schema":2,"devices":[]}'));assert.throws(()=>parseLibrary(JSON.stringify({schema:1,devices:[base,base]})));});
test('save/reload preserves active selection and detects stale revision',()=>{const store=storage();let l=saveDevice(emptyLibrary(),base);l=writeLibrary(l,store);assert.equal(readLibrary(store).activeId,base.id);assert.equal(readLibrary(store).devices[0].lengthMm,200);assert.throws(()=>writeLibrary(l,store,0));});
test('import creates distinct IDs and keeps existing profiles',()=>{const l=saveDevice(emptyLibrary(),base);const n=mergeLibrary(l,l);assert.equal(n.devices.length,2);assert.notEqual(n.devices[0].id,n.devices[1].id);});
test('refresh rate independent clock',()=>{let a={phase:0,cycles:0,running:true,last:0},b={...a};for(let i=1;i<=60;i++)a=advanceClock(a,i*1000/60,4);for(let i=1;i<=120;i++)b=advanceClock(b,i*1000/120,4);assert.ok(Math.abs(a.phase-b.phase)<1e-10);});
test('background gaps and pause do not advance phase',()=>{const c={phase:.3,cycles:1,running:true,last:0};assert.equal(advanceClock(c,5000,4).phase,.3);assert.equal(advanceClock({...c,running:false},16,4).phase,.3);});
test('blocked storage reports failure, not successful save',()=>{assert.throws(()=>writeLibrary(emptyLibrary(),{getItem:()=>null,setItem:()=>{throw Error('blocked')}}));});
