const clamp=v=>Math.max(0,Math.min(1,Number(v)||0)),HOUR=3600000;
export const MEMORY_VERSION='ANNA-MEMORY-0.57';
export function defaultMemory(){return{version:MEMORY_VERSION,episodes:[],facts:[],openThreads:[],lastProactiveAt:0,mediaState:'idle-attentive',updatedAt:Date.now()}}
export function normalizeMemory(v={}){const d=defaultMemory();return{...d,...v,episodes:Array.isArray(v.episodes)?v.episodes.slice(-240):[],facts:Array.isArray(v.facts)?v.facts.slice(-120):[],openThreads:Array.isArray(v.openThreads)?v.openThreads.slice(-40):[]}}
function ageWeight(at,now,halfLifeHours){return Math.pow(.5,Math.max(0,now-at)/HOUR/halfLifeHours)}
export function remember(input,{kind='conversation',summary='',salience=.35,valence=0,tags=[],resolved=false}={},now=Date.now()){const m=normalizeMemory(input),ep={id:now.toString(36)+'-'+Math.random().toString(36).slice(2,6),kind,summary:String(summary).slice(0,260),salience:clamp(salience),valence:Math.max(-1,Math.min(1,valence)),tags:tags.slice(0,10),at:now,resolved:Boolean(resolved)};m.episodes.push(ep);m.episodes=m.episodes.slice(-240);if(!resolved&&salience>=.65&&['conflict','promise','question','boundary'].includes(kind))m.openThreads.push({id:ep.id,kind,summary:ep.summary,at:now,weight:ep.salience});m.openThreads=m.openThreads.slice(-40);m.updatedAt=now;return m}
export function learnFact(input,{subject='user',key='',value='',confidence=.7,source='conversation'}={},now=Date.now()){const m=normalizeMemory(input);if(!key||!value)return m;const k=String(key).slice(0,80),v=String(value).slice(0,180),i=m.facts.findIndex(x=>x.subject===subject&&x.key===k);const row={subject,key:k,value:v,confidence:clamp(confidence),source,updatedAt:now};if(i>=0)m.facts[i]={...m.facts[i],...row};else m.facts.push(row);m.facts=m.facts.slice(-120);m.updatedAt=now;return m}
export function recall(input,{limit=8,tags=[]}={},now=Date.now()){const m=normalizeMemory(input),wanted=new Set(tags);return m.episodes.map(e=>{const tagBoost=e.tags.some(t=>wanted.has(t))?.18:0,half=e.salience>.75?720:e.salience>.5?240:72;return{...e,score:clamp(e.salience*ageWeight(e.at,now,half)+tagBoost+(e.resolved?0:.08))}}).sort((a,b)=>b.score-a.score).slice(0,limit)}
export function resolveThread(input,id){const m=normalizeMemory(input);m.openThreads=m.openThreads.filter(x=>x.id!==id);const e=m.episodes.find(x=>x.id===id);if(e)e.resolved=true;m.updatedAt=Date.now();return m}
export function mediaState(psyche={}){const mood=psyche.mood||{},r=psyche.relationship||{},motives=psyche.motives||{};if(mood.irritation>.55)return'idle-guarded';if(mood.sadness>.42)return'idle-withdrawn';if(mood.energy<.3)return'idle-tired';if(r.willingness>.68&&r.heat>.45)return'engaged-high';if(motives.curiosity>.62)return'idle-curious';if(mood.valence>.3)return'idle-warm';return'idle-attentive'}
export function proactiveCue(input,psyche={},now=Date.now()){const m=normalizeMemory(input),hours=(now-(m.lastProactiveAt||0))/HOUR,mo=psyche.motives||{},mood=psyche.mood||{};if(hours<6||mood.irritation>.7||mo.space>mo.connection+.25)return{shouldInitiate:false};const thread=m.openThreads.slice().sort((a,b)=>b.weight-a.weight)[0];if(thread&&hours>12&&mo.connection>.35)return{shouldInitiate:true,reason:'open-thread',cue:thread.summary};const old=recall(m,{limit:1},now)[0];if(old&&hours>24&&mo.curiosity>.5)return{shouldInitiate:true,reason:'memory-recall',cue:old.summary};return{shouldInitiate:false}}
export function markProactive(input,now=Date.now()){const m=normalizeMemory(input);m.lastProactiveAt=now;m.updatedAt=now;return m}
export function memoryContext(input,psyche={},now=Date.now()){const m=normalizeMemory(input);m.mediaState=mediaState(psyche);return{memory:m,recalled:recall(m,{limit:8},now),facts:m.facts.slice(-20),openThreads:m.openThreads.slice(-8),proactive:proactiveCue(m,psyche,now),mediaState:m.mediaState}}
