import{initialLive,waveSample,waveVisual}from'./live-engine.js';
const $=id=>document.getElementById(id),clamp=v=>Math.max(0,Math.min(1,Number(v)||0));let token=sessionStorage.getItem('nocturne.staging.token'),live=initialLive(),sessionActive=false,last=performance.now(),climaxOn=true,climax=0,lastPeak=0,peakLog=[];
function status(v,on=false){const p=$('presence');if(!p)return;p.querySelector('b').textContent=v;p.classList.toggle('live',on)}
function line(v){if($('last-line'))$('last-line').textContent=v}
function bind(id,fn){const el=$(id);if(!el)return;el.addEventListener('click',e=>{e.preventDefault();fn(e)});el.addEventListener('touchend',e=>{e.preventDefault();fn(e)},{passive:false})}
async function boot(){try{const r=await fetch('/v1/director/status',{headers:token?{'x-nocturne-session':token}:{}}),d=await r.json();if(d.sessionToken){token=d.sessionToken;sessionStorage.setItem('nocturne.staging.token',token)}status(d.openAIConfigured?'AI LIVE':'FALLBACK',true)}catch(e){status('OFFLINE');line('Director connection failed.')}}
function syncReadout(){for(const [id,k]of[['wr-pace','pace'],['wr-depth','depth'],['wr-force','force'],['wr-energy','intensity']])if($(id))$(id).textContent=Math.round(live.telemetry[k]*100)}
function setLive(on){live.running=on;sessionActive=on;const b=$('live-start');if(b)b.textContent=on?'PAUSE LIVE':'START LIVE';if(on)line('Live telemetry session started.');else line('Live telemetry paused.')}
bind('live-start',()=>setLive(!live.running));bind('climax-toggle',()=>{climaxOn=!climaxOn;$('climax-toggle').textContent='NOCTURNE ● '+(climaxOn?'ON':'OFF');if(!climaxOn)climax=0});bind('hold',()=>line('Holding current state.'));bind('change',()=>sendText('Change the current pattern.'));bind('peak',()=>line('Peak event recorded.'));bind('report',()=>{const d=$('report-dialog');if(d?.showModal)d.showModal()});bind('send',()=>{const b=$('send');b?.classList.add('press');setTimeout(()=>b?.classList.remove('press'),170);sendText($('message')?.value||'')});
for(const b of document.querySelectorAll('[data-command]')){b.addEventListener('click',e=>{e.preventDefault();sendText(b.dataset.command)});b.addEventListener('touchend',e=>{e.preventDefault();sendText(b.dataset.command)},{passive:false})}
async function sendText(text){text=String(text||'').trim();if(!text)return;if(!token){await boot();if(!token)return}const send=$('send');if(send)send.disabled=true;try{const r=await fetch('/v1/director/respond',{method:'POST',headers:{'content-type':'application/json','x-nocturne-session':token},body:JSON.stringify({text,context:{chart:{activePort:'V',lead:'AVATAR',intensity:live.telemetry.intensity,rhythm:'steady'},about:'Live beta telemetry session. Translate explicit control language into telemetry deltas.'}})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Director failed');const q=d.director||{};const changes=[];for(const [key,label]of[['pace','PACE'],['intensity','ENERGY'],['depth','DEPTH'],['force','FORCE']]){const delta=Number(q[key+'Delta']||0);if(delta){live.telemetry[key]=clamp(live.telemetry[key]+delta);changes.push(label+' '+(delta>0?'↑':'↓'))}}if(changes.length&&!live.running)setLive(true);syncReadout();if(changes.length){const t=$('change-toast');if(t){$('change-text').textContent=changes.join(' · ');t.hidden=false;setTimeout(()=>t.hidden=true,1800)}}line(q.speech||'Applied.');if($('message'))$('message').value=''}catch(e){line('Director error: '+String(e.message).slice(0,80))}finally{if(send)send.disabled=false}}
function draw(now){const dt=Math.min(80,now-last);last=now;if(live.running){const period=1.1+(1-live.telemetry.pace)*2.7;live.phase=(live.phase+dt/1000/period)%1;if(climaxOn){const drive=(live.telemetry.intensity*.38+live.telemetry.pace*.24+live.telemetry.force*.22+live.telemetry.depth*.16),rate=(drive-.48)*dt*.012;climax=clamp(climax+rate);if(climax>=.995&&now-lastPeak>4000){lastPeak=now;peakLog.push({at:Date.now(),telemetry:{...live.telemetry}});peakLog=peakLog.slice(-30);$('wave')?.classList.add('peak');setTimeout(()=>$('wave')?.classList.remove('peak'),800);climax=.72}}else climax=Math.max(0,climax-dt*.00025)}if($('climax-fill')){$('climax-fill').style.width=(climax*100)+'%';$('climax-marker').style.left=(climax*100)+'%';$('climax-value').textContent=Math.round(climax*100)}const c=$('waveform');if(c){const dpr=devicePixelRatio||1,w=c.clientWidth*dpr,h=c.clientHeight*dpr;if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d'),v=waveVisual(live),mid=h/2,force=clamp(live.telemetry.force),depth=clamp(live.telemetry.depth);x.clearRect(0,0,w,h);const hue=205-(force*200),stroke='hsla('+hue+',95%,'+(68-force*10)+'%,.94)',scroll=live.running?(now*.00008*(.6+live.telemetry.pace*3.8))%1:0;x.beginPath();if(!v.active){x.moveTo(0,mid);x.lineTo(w,mid)}else for(let i=0;i<=260;i++){const q=i/260,sampleQ=(q+scroll)%1,y=mid+waveSample(live,sampleQ,now)*h*.58;i?x.lineTo(q*w,y):x.moveTo(q*w,y)}x.strokeStyle=v.active?stroke:'rgba(190,160,210,.16)';x.lineWidth=(v.active?(1.6+force*2.7):1)*dpr;x.shadowBlur=v.active?(7+live.telemetry.intensity*18)*dpr:0;x.shadowColor=stroke;x.stroke();x.shadowBlur=0;if(v.active){const phase=.5,px=w*.5,py=mid+waveSample(live,(phase+scroll)%1,now)*h*.58,r=(5+force*3)*dpr;const glow=x.createRadialGradient(px,py,0,px,py,r*3);glow.addColorStop(0,'hsla('+hue+',100%,92%,1)');glow.addColorStop(.3,stroke);glow.addColorStop(1,'hsla('+hue+',100%,60%,0)');x.fillStyle=glow;x.beginPath();x.arc(px,py,r*3,0,Math.PI*2);x.fill();x.fillStyle='white';x.beginPath();x.arc(px,py,r,0,Math.PI*2);x.fill();const guide=h*.42*depth;x.strokeStyle='rgba(255,255,255,.08)';x.setLineDash([3*dpr,5*dpr]);x.beginPath();x.moveTo(0,mid-guide);x.lineTo(w,mid-guide);x.moveTo(0,mid+guide);x.lineTo(w,mid+guide);x.stroke();x.setLineDash([])}}const bg=$('world');if(bg){const bx=bg.getContext('2d'),bw=bg.width,bh=bg.height;if(bw&&bh&&live.running){bx.save();bx.globalCompositeOperation='lighter';const p=live.telemetry.pace,f=live.telemetry.force,d=live.telemetry.depth;for(let k=0;k<5;k++){bx.strokeStyle='hsla('+(205-f*200)+',90%,60%,'+(.025+.02*live.telemetry.intensity)+')';bx.lineWidth=(1+f*2)*devicePixelRatio;bx.beginPath();const yy=bh*(.25+k*.13);for(let xx=0;xx<=bw;xx+=bw/30){const y=yy+Math.sin(xx/bw*Math.PI*(2+p*7)+now*.001*(.3+p*2)+k)*bh*.025*d;xx?bx.lineTo(xx,y):bx.moveTo(xx,y)}bx.stroke()}bx.restore()}}requestAnimationFrame(draw)}
syncReadout();status('CONNECTING');boot();requestAnimationFrame(draw);window.__NOCTURNE_MOBILE_READY__=true;