import{initialLive,waveSample,waveVisual}from'./live-engine.js';
const $=id=>document.getElementById(id),clamp=v=>Math.max(0,Math.min(1,Number(v)||0));let token=sessionStorage.getItem('nocturne.staging.token'),live=initialLive(),sessionActive=false,last=performance.now();
function status(v,on=false){const p=$('presence');if(!p)return;p.querySelector('b').textContent=v;p.classList.toggle('live',on)}
function line(v){if($('last-line'))$('last-line').textContent=v}
function bind(id,fn){const el=$(id);if(!el)return;el.addEventListener('click',e=>{e.preventDefault();fn(e)});el.addEventListener('touchend',e=>{e.preventDefault();fn(e)},{passive:false})}
async function boot(){try{const r=await fetch('/v1/director/status',{headers:token?{'x-nocturne-session':token}:{}}),d=await r.json();if(d.sessionToken){token=d.sessionToken;sessionStorage.setItem('nocturne.staging.token',token)}status(d.openAIConfigured?'AI LIVE':'FALLBACK',true)}catch(e){status('OFFLINE');line('Director connection failed.')}}
function syncReadout(){for(const [id,k]of[['wr-pace','pace'],['wr-depth','depth'],['wr-force','force'],['wr-energy','intensity']])if($(id))$(id).textContent=Math.round(live.telemetry[k]*100)}
function setLive(on){live.running=on;sessionActive=on;const b=$('live-start');if(b)b.textContent=on?'PAUSE LIVE':'START LIVE';if(on)line('Live telemetry session started.');else line('Live telemetry paused.')}
bind('live-start',()=>setLive(!live.running));bind('hold',()=>line('Holding current state.'));bind('change',()=>sendText('Change the current pattern.'));bind('peak',()=>line('Peak event recorded.'));bind('report',()=>{const d=$('report-dialog');if(d?.showModal)d.showModal()});bind('send',()=>sendText($('message')?.value||''));
for(const b of document.querySelectorAll('[data-command]')){b.addEventListener('click',e=>{e.preventDefault();sendText(b.dataset.command)});b.addEventListener('touchend',e=>{e.preventDefault();sendText(b.dataset.command)},{passive:false})}
async function sendText(text){text=String(text||'').trim();if(!text)return;if(!token){await boot();if(!token)return}const send=$('send');if(send)send.disabled=true;try{const r=await fetch('/v1/director/respond',{method:'POST',headers:{'content-type':'application/json','x-nocturne-session':token},body:JSON.stringify({text,context:{chart:{activePort:'V',lead:'AVATAR',intensity:live.telemetry.intensity,rhythm:'steady'},about:'Live beta telemetry session. Translate explicit control language into telemetry deltas.'}})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Director failed');const q=d.director||{};const changes=[];for(const [key,label]of[['pace','PACE'],['intensity','ENERGY'],['depth','DEPTH'],['force','FORCE']]){const delta=Number(q[key+'Delta']||0);if(delta){live.telemetry[key]=clamp(live.telemetry[key]+delta);changes.push(label+' '+(delta>0?'↑':'↓'))}}if(changes.length&&!live.running)setLive(true);syncReadout();if(changes.length){const t=$('change-toast');if(t){$('change-text').textContent=changes.join(' · ');t.hidden=false;setTimeout(()=>t.hidden=true,1800)}}line(q.speech||'Applied.');if($('message'))$('message').value=''}catch(e){line('Director error: '+String(e.message).slice(0,80))}finally{if(send)send.disabled=false}}
function draw(now){const dt=Math.min(80,now-last);last=now;if(live.running){const period=1.1+(1-live.telemetry.pace)*2.7;live.phase=(live.phase+dt/1000/period)%1}const c=$('waveform');if(c){const dpr=devicePixelRatio||1,w=c.clientWidth*dpr,h=c.clientHeight*dpr;if(c.width!==w||c.height!==h){c.width=w;c.height=h}const x=c.getContext('2d'),v=waveVisual(live),mid=h/2;x.clearRect(0,0,w,h);x.beginPath();if(!v.active){x.moveTo(0,mid);x.lineTo(w,mid)}else for(let i=0;i<=180;i++){const q=i/180,y=mid+waveSample(live,q,now)*h*.58;i?x.lineTo(q*w,y):x.moveTo(q*w,y)}x.strokeStyle=v.active?'rgba(235,120,255,.92)':'rgba(190,160,210,.16)';x.lineWidth=(v.active?2:1)*dpr;x.stroke()}requestAnimationFrame(draw)}
syncReadout();status('CONNECTING');boot();requestAnimationFrame(draw);window.__NOCTURNE_MOBILE_READY__=true;