import{baseline,sensory,event}from'./matrix-core.js';import{readBlob}from'./player-storage.js';
const $=id=>document.getElementById(id),c=$('matrix'),x=c.getContext('2d',{alpha:false}),wc=$('waveform'),wx=wc.getContext('2d');
let base=null,set={motion:.4,complexity:.55,telemetry:.65,flash:.05,audioResponse:.6,visualResponse:.7,waveResponse:.65},events=[],started=0,stream=null,analyser=null,audio=0,impulses=[],videoUrl=null,focus='intensity',activePort='V',lead='AVATAR',hold=false,ports={V:{entry:35,depth:50,cycle:45,force:40,amount:50,hold:20,variation:20},A:{entry:28,depth:25,cycle:32,force:25,amount:35,hold:15,variation:15}};
const filaments=Array.from({length:24},(_,i)=>({seed:i*17.73,phase:i*.71,depth:.18+(i%9)/11,width:.5+(i%5)*.23}));
const spores=Array.from({length:190},(_,i)=>({a:i*2.399,r:(i%47)/47,z:(i%31)/31,phase:i*.43,size:.6+(i%7)*.16}));
const parse=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||'null')??d}catch{return d}};
const avatars=parse('aurelia.preview.avatars',[]),single=parse('aurelia.preview.avatar',null),media=parse('aurelia.preview.media',[]);
if(!avatars.length&&single)avatars.push(single);
function resize(){c.width=Math.min(innerWidth*devicePixelRatio,2400);c.height=Math.min(innerHeight*devicePixelRatio,1600);wc.width=Math.max(1,wc.clientWidth*devicePixelRatio);wc.height=Math.max(1,wc.clientHeight*devicePixelRatio)}
addEventListener('resize',resize);resize();const val=id=>Number($(id).value)/100;
function bus(){return{speed:val('speed'),intensity:val('intensity'),pleasure:val('pleasure'),discomfort:val('liveDiscomfort'),shock:val('shock'),rhythm:base?Math.min(1,3/base.cycleTime):.2,audio:audio*set.audioResponse}}
function filament(f,t,s,sc){const time=t*.00022*(.35+s.flow*2),hue=(s.hue*360+f.seed*3)%360,amp=sc*(.08+f.depth*.11+s.density*.035),span=sc*(.65+f.depth*.55);x.beginPath();for(let j=0;j<=48;j++){const q=j/48,u=(q-.5)*span*2,v=Math.sin(q*6.283+time+f.phase)*amp+Math.sin(q*12.1-time*.63+f.seed)*amp*.24+Math.sin(time*.9+f.phase)*sc*.025,twist=Math.cos(q*4.7+time*.4+f.phase)*sc*.06*f.depth;j?x.lineTo(u+twist,v):x.moveTo(u+twist,v)}x.strokeStyle='hsla('+hue+',88%,'+(58+f.depth*18)+'%,'+(.07+f.depth*.2)+')';x.lineWidth=(f.width+f.depth*2)*devicePixelRatio;x.shadowBlur=(8+f.depth*24)*devicePixelRatio;x.shadowColor='hsla('+hue+',100%,65%,.4)';x.stroke()}
function trace(t,s,b,port,color,offset=0){const w=wc.width,h=wc.height,mid=h/2+offset,p=ports[port],amp=h*(.07+b.intensity*.18+p.force/100*.08+b.audio*.12),period=Math.max(1.2,(101-p.cycle)/14);wx.lineWidth=1.5*devicePixelRatio;wx.shadowBlur=10*devicePixelRatio;wx.shadowColor=color;wx.strokeStyle=color;wx.beginPath();for(let i=0;i<=120;i++){const q=i/120,phase=q*Math.PI*4+t*.001*(6/period),envelope=Math.sin(Math.PI*q),y=mid+Math.sin(phase)*amp*envelope+Math.sin(phase*2.4)*amp*(p.variation/500);i?wx.lineTo(q*w,y):wx.moveTo(q*w,y)}wx.stroke()}function drawWave(t,s,b){wx.clearRect(0,0,wc.width,wc.height);if(activePort==='DUAL'){trace(t,s,b,'V','hsla('+(s.hue*360)+',95%,72%,.82)',-4*devicePixelRatio);trace(t,s,b,'A','hsla(188,90%,70%,.75)',4*devicePixelRatio)}else trace(t,s,b,activePort,activePort==='V'?'hsla('+(s.hue*360)+',95%,72%,.85)':'hsla(188,90%,70%,.8)');wx.shadowBlur=0}
function draw(t){const b=bus(),s=sensory(b,set),w=c.width,h=c.height,sc=Math.min(w,h),cx=w/2,cy=h*.45,bg=x.createRadialGradient(cx,cy,0,cx,cy,Math.max(w,h)*.75);bg.addColorStop(0,'hsl('+((s.hue*360+18)%360)+' 28% 8%)');bg.addColorStop(.42,'#070512');bg.addColorStop(1,'#010104');x.fillStyle=bg;x.fillRect(0,0,w,h);x.save();x.translate(cx,cy);x.globalCompositeOperation='lighter';for(let k=0;k<6;k++){const p=t*.00016*(.4+s.pulse)+k*1.047,r=sc*(.12+k*.085+Math.sin(p)*.012),hue=(s.hue*360+k*18)%360;x.beginPath();x.ellipse(Math.sin(p*.37)*sc*.035,Math.cos(p*.29)*sc*.025,r,r*(.68+Math.sin(p*.41)*.08),p*.08,0,Math.PI*2);x.strokeStyle='hsla('+hue+',82%,62%,'+(.03+k*.007)+')';x.lineWidth=(9-k)*devicePixelRatio;x.shadowBlur=30*devicePixelRatio;x.shadowColor='hsla('+hue+',100%,60%,.18)';x.stroke()}for(const f of filaments){x.save();x.rotate(Math.sin(f.phase+t*.00003)*.34+f.phase*.18);x.scale(.78+f.depth*.38,.78+f.depth*.38);filament(f,t,s,sc);x.restore()}x.shadowBlur=0;for(const p of spores){const drift=t*.000035*(.2+s.flow*1.7),a=p.a+drift*(.35+p.z),rr=(.06+p.r*.66)*sc,px=Math.cos(a+Math.sin(drift+p.phase)*.09)*rr,py=Math.sin(a*.92+Math.cos(drift*.8+p.phase)*.08)*rr*.72,hue=(s.hue*360+p.z*95+p.phase*5)%360;x.fillStyle='hsla('+hue+',100%,72%,'+(.07+p.z*.3+s.audio*.12)+')';x.beginPath();x.arc(px,py,p.size*devicePixelRatio*(.8+p.z*1.7),0,Math.PI*2);x.fill()}impulses=impulses.filter(q=>t-q.at<1800);for(const q of impulses){const age=(t-q.at)/1800;x.beginPath();x.arc(0,0,age*sc*.72,0,Math.PI*2);x.strokeStyle='hsla('+((s.hue*360+120*age)%360)+',100%,72%,'+((1-age)*.3)+')';x.lineWidth=(1+4*(1-age))*devicePixelRatio;x.stroke()}x.restore();x.globalCompositeOperation='source-over';x.shadowBlur=0;if(s.flash){const g=x.createRadialGradient(cx,cy,0,cx,cy,sc*.65);g.addColorStop(0,'rgba(255,255,255,'+(s.flash*.2)+')');g.addColorStop(1,'rgba(255,255,255,0)');x.fillStyle=g;x.fillRect(0,0,w,h)}drawWave(t,s,b);$('t-speed').textContent=Math.round(b.speed*100);$('t-intensity').textContent=Math.round(b.intensity*100);$('t-depth').textContent=base?Math.round(base.depth*100):50;$('t-force').textContent=base?Math.round(base.force*100):40;$('t-rhythm').textContent=(base?.rhythm||'steady').toUpperCase();$('phase').textContent=base?'SESSION '+Math.floor((performance.now()-started)/1000)+'s':'STANDBY';$('wave-value').textContent=Math.round((b.intensity*.65+b.audio*.35)*100);if(analyser){const a=new Uint8Array(analyser.frequencyBinCount);analyser.getByteFrequencyData(a);audio=a.reduce((n,v)=>n+v,0)/(a.length*255)}requestAnimationFrame(draw)}
requestAnimationFrame(draw);
for(const a of avatars){const o=document.createElement('option');o.value=a.id;o.textContent=a.name||'Avatar';$('avatar').append(o)}if(!avatars.length){const o=document.createElement('option');o.textContent='No local avatar';$('avatar').append(o)}
function clips(){const id=$('avatar').value,list=media.filter(m=>m.avatarId===id&&(m.reviewed||m.player?.reviewed));$('clip').replaceChildren();for(const m of list){const o=document.createElement('option');o.value=m.id;o.textContent=m.name||m.state||m.id;$('clip').append(o)}if(!list.length){const o=document.createElement('option');o.textContent='No reviewed clips';$('clip').append(o)}}$('avatar').onchange=clips;clips();
$('load-clip').onclick=async()=>{const id=$('clip').value;if(!id)return;const blob=await readBlob(id);if(!blob){$('avatar-label').textContent='CLIP MISSING ON THIS DEVICE';return}if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=URL.createObjectURL(blob);$('avatar-video').src=videoUrl;$('avatar-video').hidden=false;$('avatar-empty').hidden=true;const m=media.find(x=>x.id===id);$('avatar-label').textContent=(m?.name||'PERFORMANCE').toUpperCase();try{await $('avatar-video').play()}catch{}};
$('play-clip').onclick=()=>{const v=$('avatar-video');if(!v.src)return;v.paused?v.play().catch(()=>{}):v.pause()};

$('settings-toggle').onclick=()=>{$('settings').hidden=!$('settings').hidden};$('settings-close').onclick=()=>{$('settings').hidden=true};$('quick-close').onclick=()=>{$('quick').hidden=true};
function portUI(port){activePort=port;for(const id of ['port-v','port-a','port-dual'])$(id).classList.remove('active');$('port-'+(port==='DUAL'?'dual':port.toLowerCase())).classList.add('active');const edit=port==='DUAL'?'V':port,$title=$('port-title');$title.textContent=port==='DUAL'?'DUAL WAVE · EDITING PORT V':'PORT '+port+' · '+(port==='V'?'PRIMARY':'SECONDARY');const p=ports[edit];$('port-entry').value=p.entry;$('port-depth').value=p.depth;$('port-cycle').value=p.cycle;$('port-force').value=p.force;$('port-amount').value=p.amount;$('port-hold').value=p.hold;$('port-variation').value=p.variation;events.push(event('port_view',port==='V'?1:port==='A'?2:3))}
$('port-v').onclick=()=>portUI('V');$('port-a').onclick=()=>portUI('A');$('port-dual').onclick=()=>portUI('DUAL');
for(const key of ['entry','depth','cycle','force','amount','hold','variation'])$('port-'+key).oninput=()=>{const edit=activePort==='DUAL'?'V':activePort;ports[edit][key]=Number($('port-'+key).value)};
$('lead-toggle').onclick=()=>{lead=lead==='AVATAR'?'JAY':'AVATAR';$('lead-toggle').textContent=lead==='AVATAR'?'AVATAR LEADS':'JAY LEADS';$('lead-toggle').classList.toggle('active',lead==='AVATAR');events.push(event('lead_change',lead==='AVATAR'?1:2))};
$('apply').onclick=()=>{events.push(event('chart_apply',activePort==='A'?2:1));$('session-state').textContent='APPLIED'};
$('hold').onclick=()=>{hold=!hold;$('hold').classList.toggle('active',hold);$('hold').textContent=hold?'HOLDING':'HOLD';events.push(event('hold',hold?1:0))};
for(const el of document.querySelectorAll('[data-focus]'))el.onclick=()=>{focus=el.dataset.focus;$('focus-name').textContent=focus.toUpperCase();let v=focus==='depth'?(base?base.depth*100:50):focus==='force'?(base?base.force*100:40):focus==='speed'?val('speed')*100:focus==='intensity'?val('intensity')*100:50;$('focus-slider').value=v;$('focus-value').textContent=Math.round(v);$('quick').hidden=false};
$('focus-slider').oninput=()=>{const v=Number($('focus-slider').value);$('focus-value').textContent=v;if(focus==='speed')$('speed').value=v;if(focus==='intensity')$('intensity').value=v;if(base&&focus==='depth')base={...base,depth:v/100};if(base&&focus==='force')base={...base,force:v/100}};
$('audio-response').oninput=()=>{set.audioResponse=val('audio-response')};$('motion-live').oninput=()=>{set.motion=val('motion-live')};$('complexity-live').oninput=()=>{set.complexity=val('complexity-live')};$('safe-live').onchange=()=>{if($('safe-live').checked)set.flash=0};$('world-toggle').onclick=()=>location.href='/photo-space/';portUI('V');
$('start').onclick=()=>$('chart').showModal();$('form').onsubmit=e=>{if(e.submitter?.value==='cancel')return;base=baseline({mood:$('mood').value,energy:$('energy').value,discomfort:$('discomfort').value,thcEnabled:$('thc').checked,thcLevel:$('thcLevel').value,alcoholEnabled:$('alcohol').checked,alcoholLevel:$('alcoholLevel').value,entrySpeed:$('entrySpeed').value,depth:$('depth').value,cycleTime:$('cycleTime').value,force:$('force').value,rhythm:$('rhythm').value});set={...set,motion:val('motion'),complexity:val('complexity'),telemetry:val('telemetryResponse'),flash:$('safe').checked?0:val('flash')};$('motion-live').value=Math.round(set.motion*100);$('complexity-live').value=Math.round(set.complexity*100);$('safe-live').checked=$('safe').checked;started=performance.now();events=[event('session_start',1,started)];$('session-pill').classList.add('live');$('session-state').textContent='LIVE';portUI('V')};
$('impulse').onclick=()=>{const at=performance.now();events.push(event('impulse',1,at));impulses.push({at});$('shock').value=100;setTimeout(()=>$('shock').value=0,180)};
$('mic').onclick=async()=>{if(analyser){stream.getTracks().forEach(t=>t.stop());analyser=null;audio=0;$('mic').textContent='Mic off';return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const ac=new AudioContext(),src=ac.createMediaStreamSource(stream);analyser=ac.createAnalyser();analyser.fftSize=256;src.connect(analyser);$('mic').textContent='Mic on'}catch{$('mic').textContent='Mic unavailable'}};
$('fullscreen').onclick=async()=>{try{document.fullscreenElement?await document.exitFullscreen():await document.documentElement.requestFullscreen()}catch{}};
$('export').onclick=()=>{const p={standard:'NOCTURNE-IMMERSIVE-SESSION-1',world:'matrix-neural-organic-v2',avatarId:$('avatar').value||null,clipId:$('clip').value||null,baseline:base,settings:set,ports,activePort,lead,hold,events,durationMs:started?performance.now()-started:0},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(p,null,2)],{type:'application/json'}));a.download='NOCTURNE-IMMERSIVE-SESSION.json';a.click()};
window.addEventListener('pagehide',()=>{if(videoUrl)URL.revokeObjectURL(videoUrl);stream?.getTracks().forEach(t=>t.stop())});