import {mul,inverse,perspective,pose} from './world-graphics.js';
import {ENVIRONMENTS,readPhotoState,savePhotoState,environment} from './photo-environments.js';
const $=id=>document.getElementById(id),canvas=$('photo-world');
let gl,program,buffer,texture,state=readPhotoState(localStorage),session=null,ref=null,raf=0,down=null,motion=false,loading=false,loadToken=0,lastGood=null;
const VS=`attribute vec3 p;attribute vec2 uv;uniform mat4 vp;varying vec2 U;void main(){U=uv;gl_Position=vp*vec4(p,1.);}`;
const FS=`precision highp float;varying vec2 U;uniform sampler2D pano;void main(){gl_FragColor=texture2D(pano,U);}`;
function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s));return s;}
function sphere(segments=96,rings=48){const out=[],v=(u,t)=>{const a=u*Math.PI*2,b=t*Math.PI,x=Math.sin(b)*Math.sin(a),y=Math.cos(b),z=-Math.sin(b)*Math.cos(a);return[x*10,y*10,z*10,u,t];};for(let i=0;i<segments;i++)for(let j=0;j<rings;j++){const a=v(i/segments,j/rings),b=v((i+1)/segments,j/rings),c=v((i+1)/segments,(j+1)/rings),d=v(i/segments,(j+1)/rings);for(const q of [a,b,c,a,c,d])out.push(...q);}return new Float32Array(out);}
function initGL(){gl=canvas.getContext('webgl',{alpha:false,antialias:true,xrCompatible:true,powerPreference:'high-performance'});if(!gl)throw Error('WebGL is unavailable on this browser.');const v=compile(gl.VERTEX_SHADER,VS),f=compile(gl.FRAGMENT_SHADER,FS);program=gl.createProgram();gl.attachShader(program,v);gl.attachShader(program,f);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program));gl.deleteShader(v);gl.deleteShader(f);buffer=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const data=sphere();gl.bufferData(gl.ARRAY_BUFFER,data,gl.STATIC_DRAW);buffer.count=data.length/5;texture=gl.createTexture();gl.bindTexture(gl.TEXTURE_2D,texture);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MIN_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_MAG_FILTER,gl.LINEAR);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_S,gl.REPEAT);gl.texParameteri(gl.TEXTURE_2D,gl.TEXTURE_WRAP_T,gl.CLAMP_TO_EDGE);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGBA,1,1,0,gl.RGBA,gl.UNSIGNED_BYTE,new Uint8Array([12,11,16,255]));gl.disable(gl.CULL_FACE);gl.enable(gl.DEPTH_TEST);}
function resize(){const d=Math.min(devicePixelRatio||1,2),w=Math.max(1,Math.floor(innerWidth*d)),h=Math.max(1,Math.floor(innerHeight*d));if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}gl.viewport(0,0,w,h);}
function draw(vp){gl.useProgram(program);gl.uniformMatrix4fv(gl.getUniformLocation(program,'vp'),false,vp);gl.activeTexture(gl.TEXTURE0);gl.bindTexture(gl.TEXTURE_2D,texture);gl.uniform1i(gl.getUniformLocation(program,'pano'),0);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);const a=gl.getAttribLocation(program,'p'),u=gl.getAttribLocation(program,'uv');gl.enableVertexAttribArray(a);gl.vertexAttribPointer(a,3,gl.FLOAT,false,20,0);gl.enableVertexAttribArray(u);gl.vertexAttribPointer(u,2,gl.FLOAT,false,20,12);gl.drawArrays(gl.TRIANGLES,0,buffer.count);}
function browserFrame(){if(session)return;resize();gl.clearColor(.03,.025,.04,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);const proj=perspective(state.fov*Math.PI/180,canvas.width/canvas.height,.05,30),view=inverse(pose(0,0,0,state.yaw)),c=Math.cos(state.pitch),s=Math.sin(state.pitch),pitch=new Float32Array([1,0,0,0,0,c,s,0,0,-s,c,0,0,0,0,1]);draw(mul(proj,mul(pitch,view)));raf=requestAnimationFrame(browserFrame);}
function updateUI(){const env=environment(state.environment);$('env-title').textContent=env.name+'.';$('env-kind').textContent=env.kind.toUpperCase();$('env-note').textContent=env.note;$('resolution').textContent=env.resolution;$('source-link').href=env.source;$('environment-list').replaceChildren(...ENVIRONMENTS.map(x=>{const b=document.createElement('button');b.className='env-card'+(x.id===env.id?' selected':'');b.innerHTML=`<strong>${x.name}</strong><span>${x.kind} · ${x.resolution} · ${x.size}</span>`;b.onclick=()=>selectEnvironment(x.id);return b;}));savePhotoState(localStorage,state);}
async function loadImage(env){const token=++loadToken;loading=true;$('load-state').textContent='Loading '+env.resolution+'…';const img=new Image();img.crossOrigin='anonymous';img.decoding='async';await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Photographic source timed out.')),30000);img.onload=()=>{clearTimeout(timer);resolve();};img.onerror=()=>{clearTimeout(timer);reject(Error('Photographic source could not be loaded.'));};img.src=env.image;});if(token!==loadToken)return;const max=gl.getParameter(gl.MAX_TEXTURE_SIZE);if(img.width>max)throw Error(`This device supports ${max}px textures; this 8K source needs a compatible GPU/browser.`);gl.bindTexture(gl.TEXTURE_2D,texture);gl.pixelStorei(gl.UNPACK_FLIP_Y_WEBGL,false);gl.texImage2D(gl.TEXTURE_2D,0,gl.RGB,gl.RGB,gl.UNSIGNED_BYTE,img);lastGood=env.id;loading=false;$('load-state').textContent=`${env.resolution} loaded · ${img.width}×${img.height}`;}
async function selectEnvironment(id){if(loading)return;const previous=state.environment;state.environment=id;updateUI();try{await loadImage(environment(id));}catch(e){state.environment=lastGood||previous;updateUI();$('load-state').textContent=e.message;}}
function recenter(){state.yaw=0;state.pitch=0;savePhotoState(localStorage,state);}
function zoom(delta){const options=[55,65,75,85],i=options.indexOf(state.fov);state.fov=options[Math.max(0,Math.min(options.length-1,i+delta))];savePhotoState(localStorage,state);}
async function enableMotion(on){motion=on;if(on&&typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted'){motion=false;$('motion-look').checked=false;return;}}}
function orientation(e){if(!motion||session)return;if(Number.isFinite(e.alpha))state.yaw=-(e.alpha||0)*Math.PI/180;if(Number.isFinite(e.beta))state.pitch=Math.max(-1.35,Math.min(1.35,((e.beta||90)-90)*Math.PI/180));}
async function enterVR(){if(!navigator.xr||!await navigator.xr.isSessionSupported('immersive-vr'))return;session=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});await gl.makeXRCompatible();session.updateRenderState({baseLayer:new XRWebGLLayer(session,gl)});ref=await session.requestReferenceSpace('local');document.body.classList.add('in-vr');$('mode').textContent='Immersive WebXR panorama';cancelAnimationFrame(raf);session.addEventListener('end',()=>{session=null;ref=null;document.body.classList.remove('in-vr');$('mode').textContent='Browser panorama';raf=requestAnimationFrame(browserFrame);});const frame=(time,xr)=>{if(!session)return;session.requestAnimationFrame(frame);const vp=xr.getViewerPose(ref);if(!vp)return;gl.bindFramebuffer(gl.FRAMEBUFFER,session.renderState.baseLayer.framebuffer);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);for(const view of vp.views){const port=session.renderState.baseLayer.getViewport(view);gl.viewport(port.x,port.y,port.width,port.height);draw(mul(view.projectionMatrix,view.transform.inverse.matrix));}};session.requestAnimationFrame(frame);}
function bind(){canvas.onpointerdown=e=>{down={x:e.clientX,y:e.clientY,yaw:state.yaw,pitch:state.pitch};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(!down||motion)return;state.yaw=down.yaw-(e.clientX-down.x)*.004;state.pitch=Math.max(-1.35,Math.min(1.35,down.pitch-(e.clientY-down.y)*.004));};canvas.onpointerup=()=>{down=null;savePhotoState(localStorage,state);};canvas.onwheel=e=>{e.preventDefault();zoom(e.deltaY>0?1:-1);};$('zoom-in').onclick=()=>zoom(-1);$('zoom-out').onclick=()=>zoom(1);$('recenter').onclick=recenter;$('hide-panel').onclick=()=>$('panel').classList.add('hidden');$('show-panel').onclick=()=>$('panel').classList.remove('hidden');$('fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();$('motion-look').onchange=e=>enableMotion(e.target.checked);$('enter-vr').onclick=enterVR;$('retry').onclick=()=>location.reload();addEventListener('deviceorientation',orientation);addEventListener('pagehide',()=>{cancelAnimationFrame(raf);session?.end();});}
async function boot(){try{initGL();bind();updateUI();await loadImage(environment(state.environment));raf=requestAnimationFrame(browserFrame);const vr=!!(navigator.xr&&await navigator.xr.isSessionSupported('immersive-vr').catch(()=>false));$('enter-vr').disabled=!vr;$('enter-vr').textContent=vr?'Enter VR':'Browser view';}catch(e){$('fatal').hidden=false;$('fatal-message').textContent=e.message;$('load-state').textContent='Photo environment unavailable';}}
boot();
