import './quality.js';
import {NAV,TOKENS,STUDIO_VERSION,escapeHTML as e,updateAvatar,mediaForAvatar,profileFieldCount,contextSummary} from './studio-core.js';
/** Additive V0.14 UI. Preserves the existing preview data and backup keys. */
const css=document.createElement('link');css.rel='stylesheet';css.href='/studio.css';document.head.append(css);
document.body.classList.add('studio');
try { if(localStorage.getItem('aurelia.preview.about')===null){S.about.shareWithAI=false;S.about.usePhotosWithAI=false;} } catch {}
const glyphs={home:'M3 11 12 3l9 8v10h-6v-7H9v7H3Z',avatar:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8ZM4 21v-2a8 6 0 0 1 16 0v2',chat:'M4 4h16v12H9l-5 5Z',media:'M3 5h18v14H3ZM10 9l5 3-5 3Z',profile:'M5 3h14v18H5ZM9 8h6M9 12h6M9 16h4',settings:'M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6',search:'M10 17a7 7 0 1 0 0-14 7 7 0 0 0 0 14Zm5-2 6 6',plus:'M12 4v16M4 12h16',arrow:'M5 12h14m-6-6 6 6-6 6',check:'m5 12 4 4L19 6',more:'M5 12h1m5 0h1m5 0h1'};
function icon(name){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${glyphs[name]||glyphs.avatar}"/></svg>`;}
function report(text){const n=document.querySelector('.launch-note');if(n)n.textContent=text;}
function action(label,attrs='',primary=false){return `<button class="btn ${primary?'primary':'secondary'}" ${attrs}>${label}</button>`;}
const chooser=document.createElement('dialog');chooser.className='studio-dialog';chooser.setAttribute('aria-labelledby','studio-dialog-title');document.body.append(chooser);
let returnFocus=null;
function closeDialog(){chooser.close();if(returnFocus?.isConnected)returnFocus.focus();}
function modal(title,body){returnFocus=document.activeElement;chooser.innerHTML=`<header><div><span class="kicker">AURELIA STUDIO</span><h2 id="studio-dialog-title">${e(title)}</h2></div><button class="iconbutton" id="dialog-close" aria-label="Close dialog">×</button></header>${body}`;chooser.querySelector('#dialog-close').onclick=closeDialog;chooser.showModal();}
chooser.addEventListener('cancel',()=>{if(returnFocus?.isConnected)queueMicrotask(()=>returnFocus.focus());});
function flushProfileText(){if(S.page!=='about')return;const fields={'a-name':'preferredName','a-pronouns':'pronouns','a-home':'homeBase','a-work':'occupation','a-bio':'bio','a-interests':'interests','a-goals':'goals','a-comm':'communicationStyle','a-likes':'likes','a-dislikes':'dislikes','a-boundaries':'boundaries','a-people':'importantPeople','a-routines':'routines','a-notes':'aiNotes'};for(const [id,key] of Object.entries(fields)){const input=document.getElementById(id);if(input)S.about[key]=input.value.trim().slice(0,12000);}save();}
function go(page){try{flushProfileText();}catch{report('Could not save profile edits. Stay on this page and export before clearing data.');return;}closeDialog();S.vr=false;document.body.classList.remove('vrmode');nav(page);window.scrollTo(0,0);document.querySelector('h1')?.focus();}
layout=function(body,title='Workspace',eyebrow='Studio'){
 const current=S.page==='create'?'library':S.page;
 const navs=NAV.map(([p,label,g])=>`<button data-nav="${p}" class="${p===current?'active':''}" ${p===current?'aria-current="page"':''}>${icon(g)}<span>${label}</span>${p==='library'?`<small>${S.avatars.length}/4</small>`:''}</button>`).join('');
 const mobile=[NAV[0],NAV[1],NAV[3],NAV[4]].map(([p,l,g])=>`<button data-nav="${p}" class="${p===current?'active':''}" aria-label="${l}" ${p===current?'aria-current="page"':''}>${icon(g)}<span>${p==='library'?'Avatars':p==='media'?'Media':p==='about'?'About You':'Home'}</span></button>`).join('');
 return `<a class="skip-link" href="#workspace-main">Skip to workspace</a><div class="shell"><aside class="sidebar"><div class="brand"><div class="brandmark">A</div><span><strong>AURELIA</strong><small>STUDIO / 0.14</small></span></div><div class="nav-section">YOUR WORKSPACE</div><nav class="nav" aria-label="Main navigation">${navs}</nav><div class="side-bottom"><div class="local-card"><span class="status-dot"></span><strong>Saved on this device</strong><p>Live AI and cloud accounts are not connected.</p></div><button class="quiet" data-studio="palette">${icon('search')}Quick navigation <kbd>⌘ K</kbd></button></div></aside><main class="main" id="workspace-main"><div class="workspace-top"><span>Private beta <i>/</i> ${e(NAV.find(n=>n[0]===current)?.[1]||'Workspace')}</span><div><button class="iconbutton" data-studio="palette" aria-label="Open quick navigation">${icon('search')}</button><button class="iconbutton" data-studio="display" aria-label="Display preferences">${icon('settings')}</button><span class="beta-tag">FREE BETA</span></div></div><div class="topbar"><div><div class="eyebrow">${e(eyebrow)}</div><h1 tabindex="-1">${title}</h1></div></div>${body}</main></div><nav class="mobilebar" aria-label="Mobile navigation">${mobile}<button data-studio="palette" aria-label="More navigation">${icon('more')}<span>More</span></button></nav>`;
};
home=function(){
 const clips=mediaForAvatar(S.media,S.avatar?.id),fields=profileFieldCount(S.about),name=S.about?.preferredName;
 return layout(`<section class="studio-hero"><div class="hero-text"><span class="kicker">A SPACE THAT FEELS LIKE YOURS</span><h2>${name?`Make it yours,<br><em>${e(name)}.</em>`:'Your world.<br><em>Your way.</em>'}</h2><p>Shape a character, bring your context, and build a media library. Everything here stays on this browser while we prepare the connected experience.</p><div class="actions">${action(S.avatar?'Open your avatars':'Create your first avatar','data-nav="'+(S.avatar?'library':'create')+'"',true)}${action('Personalize About You','data-nav="about"')}</div><div class="hero-foot"><span class="status-dot"></span>No paywall · Four avatar slots · Device-local preview</div></div><div class="presence-art" aria-hidden="true"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="orbit orbit-c"></div><div class="art-core">A</div><span class="art-caption">A PRESENCE, IN PROGRESS</span></div></section><section class="metric-row" aria-label="Your workspace counts"><div><span>YOUR AVATARS</span><strong>${S.avatars.length}<small> / 4</small></strong><p>Free beta slots</p></div><div><span>ACTIVE LIBRARY</span><strong>${clips.length}<small> clips</small></strong><p>${S.avatar?e(S.avatar.name):'Create a character to begin'}</p></div><div><span>PERSONAL CONTEXT</span><strong>${fields}<small> / 8 fields</small></strong><p>${S.about.shareWithAI?'Profile marked for future AI use':'Profile sharing is off'}</p></div></section><div class="studio-two"><section class="card"><div class="section-heading"><div><span class="kicker">NEXT IN YOUR WORKSPACE</span><h2>Build the experience.</h2></div></div>${[['create','Design your character','Name, appearance, personality and cadence.',!!S.avatar],['about','Make the context personal','Your preferences, routines and boundaries.',fields>0],['media','Bring your first motion clip','Import a video and tag it for your character.',clips.length>0]].map(([p,t,d,done],i)=>`<button class="next-row" data-nav="${p}"><span class="step-mark ${done?'done':''}">${done?icon('check'):String(i+1).padStart(2,'0')}</span><span><strong>${t}</strong><small>${d}</small></span>${icon('arrow')}</button>`).join('')}</section><section class="card release-card"><span class="kicker">RELEASE 0.14</span><h2>Less friction.<br>More room to create.</h2><p>One consistent interface across phone and desktop. Faster navigation. Editable character cards. Searchable media. Your original preview data stays in place.</p><button class="quiet" data-studio="release">See what changed ${icon('arrow')}</button><div class="release-note">The interface is available. Live AI is still awaiting a verified server connection.</div></section></div>`,'Your workspace.','WELCOME BACK');
};
library=function(){
 return layout(`<div class="section-heading"><p class="muted">Your characters, kept separate. Choose one to open its workspace.</p>${action('＋ Create avatar','data-nav="create" '+(S.avatars.length>=4?'disabled':''),true)}</div><div class="avatar-cards">${S.avatars.map((a,i)=>`<article class="avatar-card"><div class="avatar-cover cover-${i%4}"><span class="card-initial" aria-hidden="true">${e(a.name?.slice(0,1)||'A')}</span><span class="avatar-label">${a.id===S.avatar?.id?'SELECTED':'CHARACTER '+String(i+1).padStart(2,'0')}</span></div><div class="avatar-card-body"><h2>${e(a.name)}</h2><p>Age ${e(a.age)} · ${mediaForAvatar(S.media,a.id).length} media clips</p><div class="actions">${a.id===S.avatar?.id?action('Open workspace','data-nav="companion"',true):action('Select avatar',`data-use-avatar="${e(a.id)}"`,true)}${action('Edit',`data-edit-avatar="${e(a.id)}"`)}</div></div></article>`).join('')}${S.avatars.length<4?`<button class="empty-slot" data-nav="create">${icon('plus')}<strong>${S.avatars.length?'Another possibility.':'Your first character.'}</strong><span>${4-S.avatars.length} available slots · Free beta</span></button>`:''}</div><div class="info-line">Card artwork is a placeholder, not a generated likeness. Create actual avatar media through the application when a provider is connected.</div>`,'Your avatars.','CHARACTER LIBRARY');
};
function palette(){modal('Where would you like to go?',`<label class="sr-only" for="quick-search">Search navigation</label><input id="quick-search" type="search" placeholder="Search pages or actions…" autocomplete="off"><div class="command-list">${[...NAV,['create','Create avatar','plus'],['runtime','Runtime lab','media']].map(([p,l,g])=>`<button data-command="${p}">${icon(g)}<span>${l}</span>${icon('arrow')}</button>`).join('')}</div><p class="muted small">Press Escape to close. Live AI is not connected.</p>`);chooser.querySelectorAll('[data-command]').forEach(b=>b.onclick=()=>go(b.dataset.command));chooser.querySelector('#quick-search').oninput=ev=>chooser.querySelectorAll('[data-command]').forEach(b=>b.hidden=!b.textContent.toLowerCase().includes(ev.target.value.toLowerCase()));chooser.querySelector('#quick-search').focus();}
function displayPrefs(){modal('Make room for your screen.',`<p class="muted">Adjust the workspace without changing your data.</p><div class="display-options">${action('Comfortable','data-display="comfortable"',true)}${action('Large controls','data-display="large"')}</div><p class="muted small">Large controls are useful in a headset browser. This is not immersive 3D VR.</p>${action('Export design tokens','id="export-tokens"')}`);chooser.querySelectorAll('[data-display]').forEach(b=>b.onclick=()=>{document.body.dataset.density=b.dataset.display;try{localStorage.setItem('aurelia.ui.density',b.dataset.display);}catch{}report('Display preference updated on this device.');});chooser.querySelector('#export-tokens').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(TOKENS,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='AURELIA_STUDIO_DESIGN_TOKENS_v014.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);};}
function editAvatar(id){const original=S.avatars.find(a=>a.id===id);if(!original)return;modal('Refine your character.',`<form id="avatar-edit"><label for="edit-name">Avatar name</label><input id="edit-name" name="name" maxlength="40" required value="${e(original.name)}"><label for="edit-age">Character age</label><input id="edit-age" name="age" type="number" min="18" max="120" required value="${e(original.age)}"><label for="edit-notes">Creative direction</label><textarea id="edit-notes" name="studioNotes" maxlength="2000" placeholder="Notes for appearance, personality or future generation…">${e(original.studioNotes||'')}</textarea><p class="muted small">These are saved design notes, not an instruction sent to a model. Editing preserves the character ID and media links.</p><div id="edit-error" role="alert"></div><div class="actions">${action('Save changes','type="submit"',true)}${action('Cancel','type="button" id="edit-cancel"')}</div></form>`);chooser.querySelector('#edit-cancel').onclick=closeDialog;chooser.querySelector('#avatar-edit').onsubmit=ev=>{ev.preventDefault();try{const stored=JSON.parse(localStorage.getItem('aurelia.preview.avatars')||'[]');const latest=stored.find(a=>a.id===id);if(latest&&JSON.stringify(latest)!==JSON.stringify(original))throw Error('This character changed in another tab. Reload before saving; your edits remain in this dialog.');const next=updateAvatar(original,Object.fromEntries(new FormData(ev.target)));const before=S.avatars;const active=S.avatar;S.avatars=S.avatars.map(a=>a.id===id?next:a);if(S.avatar?.id===id)S.avatar=next;try{save();}catch(err){S.avatars=before;S.avatar=active;throw err;}closeDialog();render();report('Character updated on this device.');}catch(err){chooser.querySelector('#edit-error').textContent=err.message;}};}
function attachMediaFilter(){const list=document.querySelector('.mediaitem')?.parentElement;if(!list)return;const controls=document.createElement('div');controls.className='media-filter';controls.innerHTML='<label class="sr-only" for="clip-search">Search clips</label><input type="search" id="clip-search" placeholder="Search clips…"><label class="sr-only" for="clip-state">Filter state</label><select id="clip-state"><option value="all">All states</option></select><p id="clip-results" class="small muted" role="status"></p>';list.before(controls);const pool=mediaForAvatar(S.media,S.avatar?.id);const states=[...new Set(pool.map(m=>m.state))].sort();controls.querySelector('select').insertAdjacentHTML('beforeend',states.map(s=>`<option value="${e(s)}">${e(s.replaceAll('_',' '))}</option>`).join(''));const rows=[...list.querySelectorAll('.mediaitem')];const filter=()=>{const q=controls.querySelector('input').value.trim().toLowerCase(),state=controls.querySelector('select').value;let visible=0;rows.forEach((r,i)=>{const item=pool[i];const match=r.textContent.toLowerCase().includes(q)&&(state==='all'||item?.state===state);r.hidden=!match;if(match)visible++;});controls.querySelector('#clip-results').textContent=`${visible} of ${rows.length} clips${!visible?' · No matches':''}`;};controls.oninput=filter;controls.onchange=filter;filter();}
function contextualPolish(){
 if(S.page==='about'){
  const groups=document.querySelectorAll('.aboutgrid');if(groups[1]){const panel=document.createElement('details');panel.className='profile-details';panel.innerHTML='<summary>Preferences, boundaries & routines <span>Optional detail</span></summary>';groups[1].before(panel);panel.append(groups[1]);}
  const card=document.querySelector('.contextscore');if(card)card.innerHTML=`<strong>${profileFieldCount(S.about)} <small>/ 8</small></strong><span>profile fields filled, not an AI score</span>`;
  const photoAI=document.querySelector('#a-photo-ai');if(photoAI)photoAI.checked=false;
 }
 if(S.page==='media'){
  attachMediaFilter();document.querySelectorAll('.analysisgrid span').forEach(n=>{if(n.textContent==='Seam score')n.textContent='Frame similarity';});
  const stage=document.querySelector('.mediastage');if(stage){const p=document.createElement('p');p.className='small muted';p.textContent='Frame similarity is only a visual heuristic. Review motion, timing and audio before approving a loop.';stage.after(p);}
 }
 if(S.page==='companion'){
  const input=document.querySelector('#chat-input');if(input&&S.avatar){const k='aurelia.unsent.'+S.avatar.id;try{input.value=sessionStorage.getItem(k)||'';}catch{}input.oninput=()=>{try{sessionStorage.setItem(k,input.value);}catch{report('This tab cannot preserve the draft.');}};input.placeholder='Draft a message here. Nothing is sent while AI is disconnected.';const bar=document.createElement('div');bar.className='composer-review';bar.innerHTML=action('Review context','data-studio="context"')+'<span>Draft only · This tab · Not sent</span>';input.closest('form').after(bar);}
 }
 document.querySelectorAll('input:not([type=checkbox]):not([type=range]),textarea,select').forEach(el=>{if(el.labels?.length)return;const label=el.previousElementSibling;if(label?.tagName==='LABEL'&&el.id)label.htmlFor=el.id;});
 document.querySelectorAll('[data-edit-avatar]').forEach(b=>b.onclick=()=>editAvatar(b.dataset.editAvatar));
}
function contextReview(){const summary=contextSummary(S.about);modal('Review before sharing.',`<div class="context-review"><div><span>Selected character</span><strong>${e(S.avatar?.name||'None')}</strong></div><div><span>Profile sharing preference</span><strong>${summary.shared?'Marked for future use':'Off'}</strong></div><div><span>Photos attached to this draft</span><strong>None</strong></div></div><p class="muted small">${summary.fields.length?'Enabled profile fields: '+summary.fields.map(e).join(', '):'No profile fields are enabled.'}</p><div class="notice">This preview sends no text or photos. The private-backend candidate checks account and per-photo permission on every send and requires explicit per-message attachments.</div>`);}
const priorRender=render;render=function(){priorRender();contextualPolish();document.querySelectorAll('.brand small').forEach(n=>n.textContent='STUDIO / 0.14');};
document.addEventListener('click',event=>{const b=event.target.closest?.('[data-studio]');if(!b)return;const a=b.dataset.studio;if(a==='palette')palette();if(a==='display')displayPrefs();if(a==='context')contextReview();if(a==='release')modal('Studio 0.14',`<p class="muted">A shared design system, an adaptive navigation shell, editable character cards, a focused profile editor and searchable media. No new account or paid service is required for this preview.</p><div class="notice">Live AI and cloud-account sync remain unconnected. Local previews are not cloud backups.</div>`);});
document.addEventListener('click',event=>{if(event.target.closest?.('#export-device')){try{flushProfileText();}catch{event.preventDefault();event.stopImmediatePropagation();report('Profile save failed; backup was not started.');}}},true);
document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(chooser.open)closeDialog();else palette();}});
try{document.body.dataset.density=localStorage.getItem('aurelia.ui.density')==='large'?'large':'comfortable';}catch{}
const skip=document.createElement('noscript');skip.textContent='This preview requires JavaScript.';document.body.append(skip);
render();report('Studio 0.14 · Existing data preserved · Live AI not connected');
