import{directorBias}from'./live-bridge.js';import{groundingContext}from'./anna-grounding.js';import{remember,normalizeMemory}from'./anna-memory.js';import{event as psycheEvent,normalize as normalizePsyche}from'./anna-psyche.js';import{cloudManifest,stateById,baseStateId,familyCandidates}from'./video-state-core.js';
const $=id=>document.getElementById(id),clamp=v=>Math.max(0,Math.min(1,Number(v)||0)),canvas=$('xr-canvas'),patternCore=globalThis.NocturneVrPatterns;
// Quest immersive rendering is owned exclusively by vr-fallback.js. Do not reserve the XR canvas here.
const gl=null;
let xrSession=null,refSpace=null,inputs=new Map(),phase=0,lastT=0,lastPeak=0,token=sessionStorage.getItem('nocturne.staging.token');let vrImmersiveActive=false,autopilot=localStorage.getItem('nocturne.vr.autopilot.v1')==='on',autopilotBusy=false,currentVideoState=localStorage.getItem('nocturne.vr.video-state.v1')||'A01',availableVideoStates=[],vrMotion={phase:0,cycle:0,direction:'STILL',envelope:0},vrControllers=[],lastCycleDecision=-1,lastCycleDecisionAt=0;
const VR_SESSION_KEY='nocturne.vr.session.v070',EMBODIED_STATE_KEY='nocturne.embodied.state.v071',POSITION_VALUES=['back','doggy','side','standing','squat'];
let embodiedState=localStorage.getItem(EMBODIED_STATE_KEY)||'attentive',position=POSITION_VALUES.includes(localStorage.getItem('nocturne.vr.position.v1'))?localStorage.getItem('nocturne.vr.position.v1'):'back';
let visualCfg={videoEnabled:localStorage.getItem('nocturne.vr.video-enabled.v1')!=='off',videoSound:localStorage.getItem('nocturne.vr.video-sound.v1')==='on',toolSolid:localStorage.getItem('nocturne.vr.tool-solid.v1')!=='off',mannequinTexture:localStorage.getItem('nocturne.vr.mannequin-texture.v1')!=='off',voiceGuidance:localStorage.getItem('nocturne.vr.voice-guidance.v1')!=='off',commandMode:localStorage.getItem('nocturne.vr.command-mode.v1')!=='off',waveScale:Math.max(.5,Math.min(2,Number(localStorage.getItem('nocturne.vr.wave-scale.v1'))||1)),waveMotion:Math.max(.5,Math.min(1.8,Number(localStorage.getItem('nocturne.vr.wave-motion.v1'))||1))},lastSpokenAt=0;
let telemetry={pace:0,depth:0,force:0,intensity:0,entrySpeedS:3,cycleTimeS:3,initialized:false,startedAt:0},pattern=localStorage.getItem('nocturne.vr.pattern.v1')||'steady',hapticMode=localStorage.getItem('nocturne.vr.haptic-pattern.v1')||'auto',dynamicStrokes=localStorage.getItem('nocturne.vr.dynamic-strokes.v1')!=='off',hapticStrength=.7,recordedPattern=[],cadence=0,vrDraw=new Map();
const VR_CHART_KEY='nocturne.vr.chart.v1',VR_CONTINUITY_KEY='nocturne.vr.continuity.v1';
let chartState=loadChartState(),micListening=false,micRecognition=null;
function loadChartState(){try{const s=JSON.parse(localStorage.getItem(VR_CHART_KEY)||'{}');return{index:Math.max(1,Number(s.index)||1),strokes:Math.max(0,Number(s.strokes)||0),target:Math.max(4,Math.min(200,Number(s.target)||40)),peaks:Math.max(0,Number(s.peaks)||0),history:Array.isArray(s.history)?s.history.slice(-24):[]}}catch{return{index:1,strokes:0,target:40,peaks:0,history:[]}}}
function saveChartState(){try{localStorage.setItem(VR_CHART_KEY,JSON.stringify(chartState))}catch{}syncChartHUD();window.dispatchEvent(new CustomEvent('nocturne:vr-chart-state',{detail:{...chartState}}))}
function syncChartHUD(){text('vr-chart-number',String(chartState.index).padStart(2,'0'));text('vr-chart-strokes',chartState.strokes);text('vr-chart-target',chartState.target);text('vr-peak-count',chartState.peaks)}
function chartSnapshot(){return{index:chartState.index,strokes:chartState.strokes,target:chartState.target,peaks:chartState.peaks,telemetry:{...telemetry},pattern,position,videoState:currentVideoState,at:Date.now()}}
function applyChartSnapshot(s){if(!s)return;telemetry={...telemetry,...(s.telemetry||{})};pattern=s.pattern||pattern;if(POSITION_VALUES.includes(s.position))position=s.position;if(s.videoState)setVrVideoState(s.videoState,'chart');chartState.index=Math.max(1,Number(s.index)||chartState.index);chartState.strokes=Math.max(0,Number(s.strokes)||0);chartState.target=Math.max(4,Math.min(200,Number(s.target)||40));chartState.peaks=Math.max(0,Number(s.peaks)||0);saveTelemetry();saveChartState();syncHUD()}
function archiveCurrentChart(){chartState.history=chartState.history.filter(x=>x.index!==chartState.index);chartState.history.push(chartSnapshot());chartState.history=chartState.history.slice(-24)}
function nextChart(reason='manual'){archiveCurrentChart();const nextIndex=chartState.index+1,existing=chartState.history.find(x=>x.index===nextIndex);if(existing)applyChartSnapshot(existing);else{chartState.index=nextIndex;chartState.strokes=0;chartState.peaks=0;saveChartState()}rememberVr('chart','Advanced to chart '+chartState.index+' ('+reason+').',['vr','chart'],.45);window.dispatchEvent(new CustomEvent('nocturne:vr-chart-next',{detail:{reason,index:chartState.index}}));if(autopilot)setTimeout(()=>autopilotTick(true),100)}
function prevChart(){archiveCurrentChart();const prev=Math.max(1,chartState.index-1),existing=chartState.history.find(x=>x.index===prev);if(existing)applyChartSnapshot(existing);else{chartState.index=prev;chartState.strokes=0;chartState.peaks=0;saveChartState()}rememberVr('chart','Moved back to chart '+chartState.index+'.',['vr','chart'],.3)}
function rememberVr(kind,summary,tags=['vr'],salience=.4){try{let m=normalizeMemory(localJSON('nocturne.anna.memory.v057'));m=remember(m,{kind,summary,salience,tags,resolved:true});localStorage.setItem('nocturne.anna.memory.v057',JSON.stringify(m));const q=JSON.parse(localStorage.getItem(VR_CONTINUITY_KEY)||'[]');q.push({kind,summary,tags,at:Date.now()});localStorage.setItem(VR_CONTINUITY_KEY,JSON.stringify(q.slice(-120)))}catch{}}
function psycheVr(type,note='',salience=.45){try{let p=normalizePsyche(localJSON('nocturne.anna.psyche.v056'));p=psycheEvent(p,type,{salience,note,tags:['vr']});localStorage.setItem('nocturne.anna.psyche.v056',JSON.stringify(p))}catch{}}

function loadVrSession(){try{const shared=window.NocturneSession?.snapshot?.();const s=shared?.initialized?shared:JSON.parse(sessionStorage.getItem(VR_SESSION_KEY)||'{}');if(!s.initialized){telemetry={...telemetry,pace:0,depth:0,force:0,intensity:0,initialized:false,startedAt:0};cadence=0;return false}telemetry={...telemetry,pace:clamp(s.pace),depth:clamp(s.depth),force:clamp(s.force),intensity:clamp(s.intensity),entrySpeedS:Math.max(.5,Math.min(10,Number(s.entrySpeedS)||3)),cycleTimeS:Math.max(.7,Math.min(10,Number(s.cycleTimeS)||3)),initialized:true,startedAt:Number(s.startedAt)||Date.now()};pattern=patternCore?.patterns?.includes(s.pattern)?s.pattern:(patternCore?.patterns?.includes(pattern)?pattern:'steady');hapticMode=patternCore?.hapticModes?.includes(s.hapticMode)?s.hapticMode:hapticMode;dynamicStrokes=s.dynamicStrokes!==undefined?Boolean(s.dynamicStrokes):dynamicStrokes;recordedPattern=Array.isArray(s.recordedPattern)?s.recordedPattern.slice(0,256):recordedPattern;cadence=Math.max(0,Math.min(100,Number(s.cadence)||0));if(s.videoState)currentVideoState=String(s.videoState);if(s.embodied)setEmbodiedState(String(s.embodied),'session');if(POSITION_VALUES.includes(s.position))position=s.position;return true}catch{return false}}
loadVrSession();
function text(id,v){const e=$(id);if(e)e.textContent=v}
function syncHUD(){const p=telemetry.initialized?Math.round(telemetry.pace*100):0,d=telemetry.initialized?Math.round(telemetry.depth*100):0,f=telemetry.initialized?Math.round(telemetry.force*100):0,e=telemetry.initialized?Math.round(telemetry.intensity*100):0;text('pace',p);text('depth',d);text('force',f);text('energy',e);text('diag-session',telemetry.initialized?'READY':'ZERO');for(const [id,v]of[['vr-pace-range',p],['vr-depth-range',d],['vr-force-range',f],['vr-energy-range',e]]){const el=$(id);if(el&&document.activeElement!==el)el.value=v}for(const [id,v]of[['vr-pace-out',p],['vr-depth-out',d],['vr-force-out',f],['vr-energy-out',e],['vr-wave-scale-out',Math.round(visualCfg.waveScale*100)],['vr-wave-motion-out',Math.round(visualCfg.waveMotion*100)]])text(id,v);if($('vr-position'))$('vr-position').value=position;if($('vr-pattern'))$('vr-pattern').value=pattern;if($('vr-haptic-pattern'))$('vr-haptic-pattern').value=hapticMode;const states=[['vr-video-toggle',visualCfg.videoEnabled,'VIDEO'],['vr-video-sound',visualCfg.videoSound,'VIDEO AUDIO'],['vr-tool-solid',visualCfg.toolSolid,'TOOL SOLID'],['vr-voice',visualCfg.voiceGuidance,'AI VOICE'],['vr-command-mode',visualCfg.commandMode,'AI COMMANDS'],['vr-dynamic-strokes',dynamicStrokes,'DYNAMIC STROKES']];for(const [id,on,label]of states){const el=$(id);if(!el)continue;el.setAttribute('aria-pressed',String(on));el.textContent=label+' '+(on?'ON':'OFF')}if($('vr-wave-scale')&&document.activeElement!==$('vr-wave-scale'))$('vr-wave-scale').value=Math.round(visualCfg.waveScale*100);if($('vr-wave-motion')&&document.activeElement!==$('vr-wave-motion'))$('vr-wave-motion').value=Math.round(visualCfg.waveMotion*100);syncChartHUD()}
function visualPayload(){return{...visualCfg,position}}
function persistVisual(){try{localStorage.setItem('nocturne.vr.video-enabled.v1',visualCfg.videoEnabled?'on':'off');localStorage.setItem('nocturne.vr.video-sound.v1',visualCfg.videoSound?'on':'off');localStorage.setItem('nocturne.vr.tool-solid.v1',visualCfg.toolSolid?'on':'off');localStorage.setItem('nocturne.vr.mannequin-texture.v1',visualCfg.mannequinTexture?'on':'off');localStorage.setItem('nocturne.vr.voice-guidance.v1',visualCfg.voiceGuidance?'on':'off');localStorage.setItem('nocturne.vr.command-mode.v1',visualCfg.commandMode?'on':'off');localStorage.setItem('nocturne.vr.wave-scale.v1',String(visualCfg.waveScale));localStorage.setItem('nocturne.vr.wave-motion.v1',String(visualCfg.waveMotion));localStorage.setItem('nocturne.vr.position.v1',position)}catch{}window.dispatchEvent(new CustomEvent('nocturne:vr-visual-config',{detail:visualPayload()}));syncHUD()}
async function bootDirector(){try{const r=await fetch('/v1/director/status',{headers:token?{'x-nocturne-session':token}:{}}),d=await r.json();if(d.sessionToken){token=d.sessionToken;sessionStorage.setItem('nocturne.staging.token',token)}vrAiStatus(d.openAIConfigured?'AI LIVE':'AI FALLBACK');return d}catch{vrAiStatus('AI OFFLINE');return null}}
function localJSON(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}
function vrAiStatus(textValue){window.dispatchEvent(new CustomEvent('nocturne:vr-ai-status',{detail:{text:String(textValue||'AI READY')}}))}

async function refreshAvailableVideoStates(){try{const m=await cloudManifest();availableVideoStates=(m.states||[]).map(x=>x.id).filter(Boolean);text('diag-media',availableVideoStates.length?(availableVideoStates.length+' STATES'):'MISSING');return availableVideoStates}catch{text('diag-media','OFFLINE');return availableVideoStates}}
function chooseAvailableVideoState(id){id=String(id||'').toUpperCase();if(!stateById(id))id='A01';if(!availableVideoStates.length||availableVideoStates.includes(id))return id;const base=baseStateId(id),family=familyCandidates(base||id,[]).filter(x=>availableVideoStates.includes(x));return family[0]||(['A01','A02','A00'].find(x=>availableVideoStates.includes(x)))||id}
function embodiedFromVideo(id=''){id=String(id).toUpperCase();if(/^A18/.test(id))return'intense';if(/^A19/.test(id)||id==='A20')return'recovering';const m={A00:'calm',A01:'calm',A02:'attentive',A03:'attentive',A04:'curious',A05:'focused',A06:'focused',A07:'attentive',A08:'playful',A09:'playful',A10:'assertive',A11:'attentive',A12:'irritated',A13:'withdrawn',A14:'recovering',A15:'attentive',A16:'focused',A17:'intense'};return m[id]||'attentive'}
function setEmbodiedState(next,reason='director'){embodiedState=next||'attentive';try{localStorage.setItem(EMBODIED_STATE_KEY,embodiedState)}catch{}window.dispatchEvent(new CustomEvent('nocturne:embodied-state',{detail:{state:embodiedState,reason}}));const el=$('vr-video-state');if(el)el.textContent=embodiedState.toUpperCase();}
function stateHapticFactor(){return embodiedState==='intense'?1.22:embodiedState==='assertive'?1.08:embodiedState==='withdrawn'?.42:embodiedState==='recovering'?.62:embodiedState==='playful'?.92:1}

function setVrVideoState(id,reason='director'){const chosen=chooseAvailableVideoState(id),changed=chosen!==currentVideoState;currentVideoState=chosen;try{localStorage.setItem('nocturne.vr.video-state.v1',chosen)}catch{}setEmbodiedState(embodiedFromVideo(chosen),reason);window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:chosen,reason,changed,videoSound:visualCfg.videoSound}}));return chosen}
function saveTelemetry(){try{const s={...telemetry,pattern,hapticMode,dynamicStrokes,recordedPattern:recordedPattern.slice(0,256),cadence,position,videoState:currentVideoState,embodied:embodiedState,visuals:visualPayload(),updatedAt:Date.now()};sessionStorage.setItem(VR_SESSION_KEY,JSON.stringify(s));localStorage.setItem('nocturne.vr.pattern.v1',pattern);localStorage.setItem('nocturne.vr.haptic-pattern.v1',hapticMode);localStorage.setItem('nocturne.vr.dynamic-strokes.v1',dynamicStrokes?'on':'off');localStorage.setItem('nocturne.telemetry.v1',JSON.stringify({pace:telemetry.pace,depth:telemetry.depth,force:telemetry.force,intensity:telemetry.intensity,pattern,hapticMode,dynamicStrokes,cadence,position,videoState:currentVideoState,updatedAt:s.updatedAt}));window.NocturneSession?.commit?.(s,'vr-runtime')}catch{}}
function applyDirector(q={},source='director'){
  const priorPace=telemetry.pace;const setNum=(key,target,delta)=>{if(Number.isFinite(target))telemetry[key]=clamp(target);else if(Number.isFinite(delta)&&delta)telemetry[key]=clamp(telemetry[key]+delta)};
  setNum('pace',q.paceTarget,q.paceDelta);setNum('depth',q.depthTarget,q.depthDelta);setNum('force',q.forceTarget,q.forceDelta);setNum('intensity',q.intensityTarget,q.intensityDelta);if(Math.abs(telemetry.pace-priorPace)>.0001)telemetry.cycleTimeS=Math.max(.7,Math.min(10,5-telemetry.pace*4.3));
  if(patternCore?.patterns?.includes(q.pattern)&&q.pattern!=='keep')pattern=q.pattern;
  if(patternCore?.hapticModes?.includes(q.hapticMode)&&q.hapticMode!=='keep')hapticMode=q.hapticMode;
  if(typeof q.dynamicStrokes==='boolean')dynamicStrokes=q.dynamicStrokes;
  if(q.videoState&&q.videoState!=='keep')setVrVideoState(q.videoState,source);if(q.position&&q.position!=='keep'&&POSITION_VALUES.includes(q.position))position=q.position;
  saveTelemetry();persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-director-state',{detail:{source,videoState:currentVideoState,telemetry:{...telemetry},pattern,position,speech:String(q.speech||''),at:Date.now()}}));return q;
}
function directorContext(auto=autopilot){const g=groundingContext();return{about:'Anna guides the immersive VR session as an active character, not a passive dashboard. She may take initiative and give concise imperative cues when command mode is enabled, while keeping the user in control. Her voice is grounded in Anna Mikhailovna Sokolova’s individual Saint Petersburg biography, Russian-native language background, reserved directness, precision and dry humor. Do not stereotype Russian women or generalize nationality into personality. Keep every command tied to live telemetry, chart state, controller input, user feedback and continuity. If the user reports a peak, acknowledge it and guide recovery or the next chart.',grounding:g,psyche:localJSON('nocturne.anna.psyche.v056'),memory:localJSON('nocturne.anna.memory.v057'),continuity:localJSON(VR_CONTINUITY_KEY),experience:{...localJSON('nocturne.anna.experience.v061'),availableVideoStates,visuals:visualPayload()},mode:'vr-live',motion:{...vrMotion},controllers:vrControllers,chart:{index:chartState.index,strokes:chartState.strokes,target:chartState.target,peaks:chartState.peaks,activePort:'V',lead:'AVATAR',pace:telemetry.pace,depth:telemetry.depth,force:telemetry.force,intensity:telemetry.intensity,rhythm:pattern,hapticMode,dynamicStrokes,availablePatterns:patternCore?.patterns||[],position,videoState:currentVideoState,autopilot:auto,commandMode:visualCfg.commandMode,entrySpeedS:telemetry.entrySpeedS,cycleTimeS:telemetry.cycleTimeS},recent:[]}}

function chatState(state,message){const line=$('vr-line'),button=$('vr-send');if(line){line.dataset.state=state;line.textContent=message}if(button){button.dataset.state=state;button.textContent=state==='sending'?'SENT':state==='thinking'?'…':'SEND'}}
function speakGuide(message,force=false){const s=String(message||'').trim();if(!visualCfg.voiceGuidance||!s||!('speechSynthesis'in window))return false;const now=Date.now();if(!force&&now-lastSpokenAt<7000)return false;lastSpokenAt=now;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(s.slice(0,220));u.rate=.96;u.pitch=.94;u.volume=.92;speechSynthesis.speak(u);return true}catch{return false}}
async function sendChat(textOverride=''){const input=$('vr-message'),value=String(textOverride||input?.value||'').trim();if(!value)return;const button=$('vr-send');if(button)button.disabled=true;rememberVr('conversation','User in VR: '+value.slice(0,180),['vr','conversation'],.45);psycheVr('MEANINGFUL_CONTACT','VR conversation',.4);chatState('sending','Message received · sending to Anna…');vrAiStatus('AI RECEIVED');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{if(!token)await bootDirector();chatState('thinking','Message received · Anna is thinking…');vrAiStatus('AI THINKING');const r=await fetch('/v1/director/respond',{method:'POST',signal:controller.signal,headers:{'content-type':'application/json','x-nocturne-session':token||''},body:JSON.stringify({text:value,context:directorContext(false)})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Director unavailable');applyDirector(d.director||{},'chat');const speech=d.director?.speech||'I heard you.';chatState('done',speech);rememberVr('conversation','Anna in VR: '+speech.slice(0,180),['vr','anna','conversation'],.42);if(speech)speakGuide(speech,true);vrAiStatus('AI APPLIED');if(input)input.value=''}catch(e){vrAiStatus('AI ERROR');chatState('error',e?.name==='AbortError'?'Anna did not answer within 18 seconds. Your message was received; try Send again.':'Chat error: '+String(e.message).slice(0,100))}finally{clearTimeout(timer);if(button)button.disabled=false;if(button)button.textContent='SEND'}}
$('vr-send')?.addEventListener('click',()=>sendChat());$('vr-message')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChat()}});
function stopMicChat(){try{micRecognition?.stop?.()}catch{}micListening=false;for(const id of ['vr-mic','vr-mic-chat']){const b=$(id);if(b){b.setAttribute('aria-pressed','false');b.textContent=id==='vr-mic'?'MIC CHAT':'MIC'}}}
function startMicChat(){
  if(micListening){stopMicChat();return}
  const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){chatState('error','Microphone speech recognition is not available in this browser.');return}
  try{
    micRecognition=new SR();micRecognition.lang='en-US';micRecognition.interimResults=false;micRecognition.continuous=false;micRecognition.maxAlternatives=1;
    micRecognition.onstart=()=>{micListening=true;for(const id of ['vr-mic','vr-mic-chat']){const b=$(id);if(b){b.setAttribute('aria-pressed','true');b.textContent='LISTENING…'}}chatState('listening','Listening… speak to Anna.')};
    micRecognition.onresult=e=>{const t=String(e.results?.[0]?.[0]?.transcript||'').trim();if(t){const input=$('vr-message');if(input)input.value=t;sendChat(t)}};
    micRecognition.onerror=e=>chatState('error','Mic error: '+String(e.error||'unavailable'));
    micRecognition.onend=()=>stopMicChat();micRecognition.start();
  }catch(e){chatState('error','Mic could not start: '+String(e.message||e).slice(0,90));stopMicChat()}
}
$('vr-mic')?.addEventListener('click',startMicChat);$('vr-mic-chat')?.addEventListener('click',startMicChat);
async function autopilotTick(force=false){if(!telemetry.initialized)return;if((!autopilot&&!force)||autopilotBusy||(!vrImmersiveActive&&!force))return;autopilotBusy=true;vrAiStatus('AI CHOOSING');try{if(!token)await bootDirector();if(!availableVideoStates.length)await refreshAvailableVideoStates();const directive=visualCfg.commandMode?'Take initiative. Give one concise, actionable command the user can follow now when useful (for example hold, slower, deeper, change rhythm, or prepare for the next chart), then choose coherent telemetry/pattern/position/video updates.':'Continue coherently without commanding the user unless necessary.';const r=await fetch('/v1/director/respond',{method:'POST',headers:{'content-type':'application/json','x-nocturne-session':token||''},body:JSON.stringify({text:'Continue immersive VR in sync with the current motion cycle and chart progression. '+directive+' Preserve continuity from prior charts and user feedback.',context:directorContext(true)})}),d=await r.json();if(r.ok){applyDirector(d.director||{},'autopilot');vrAiStatus('AI APPLIED');if(d.director?.speech&&d.director.speech.length<220){chatState('done',d.director.speech);rememberVr('ai-command','Anna command/guidance: '+d.director.speech.slice(0,180),['vr','command'],.38);speakGuide(d.director.speech,false)}}else vrAiStatus('AI ERROR')}catch{vrAiStatus('AI ERROR')}finally{autopilotBusy=false}}
async function pulse(src,s,d){const gp=src?.gamepad,acts=[];if(!gp)return false;if(gp.vibrationActuator)acts.push(gp.vibrationActuator);for(const a of gp.hapticActuators||[])acts.push(a);for(const a of acts){try{if(a.pulse)await a.pulse(clamp(s),d);else if(a.playEffect)await a.playEffect('dual-rumble',{duration:d,strongMagnitude:clamp(s),weakMagnitude:clamp(s*.6)})}catch{}}return acts.length>0}
const allPulse=(s,d)=>Promise.all([...inputs.values()].map(x=>pulse(x,s,d)));
async function peak(){await allPulse(1,95);setTimeout(()=>allPulse(.9,125),150);setTimeout(()=>allPulse(1,180),320)}
async function registerUserPeak(source='button'){chartState.peaks++;saveChartState();await peak();rememberVr('peak','User reported a peak in VR on chart '+chartState.index+'.',['vr','peak','chart'],.9);psycheVr('POSITIVE','User reported peak in VR',.75);window.dispatchEvent(new CustomEvent('nocturne:vr-user-peak',{detail:{source,chart:chartState.index,peaks:chartState.peaks,at:Date.now()}}));chatState('done','Peak recorded. Anna is adjusting the next phase.');vrAiStatus('PEAK RECORDED');setTimeout(()=>autopilotTick(true),120)}
function updateInputs(t){for(const src of inputs.values()){const gp=src.gamepad,tr=gp?.buttons?.[0]?.value||0,gr=gp?.buttons?.[1]?.value||0,x=gp?.axes?.[2]??gp?.axes?.[0]??0,y=gp?.axes?.[3]??gp?.axes?.[1]??0,el=$(src.handedness+'-state');if(el)el.textContent='trigger '+tr.toFixed(2)+' · grip '+gr.toFixed(2)+' · stick '+x.toFixed(2)+','+y.toFixed(2);if(telemetry.initialized)telemetry.force=clamp(Math.max(telemetry.force*.94,tr,gr));if(telemetry.initialized&&tr>.92&&gr>.92&&t-lastPeak>2500){lastPeak=t;peak()}}syncHUD()}
function controllerDraw(frame){if(!refSpace)return;for(const src of inputs.values()){const gp=src.gamepad,gr=gp?.buttons?.[1]?.value||0,tr=gp?.buttons?.[0]?.value||0;let d=vrDraw.get(src)||{active:false,ys:[]};if(gr>.75&&tr<.25){const p=frame.getPose(src.targetRaySpace,refSpace);if(p){if(!d.active)d={active:true,ys:[]};d.ys.push(p.transform.position.y);if(d.ys.length>180)d.ys.shift();vrDraw.set(src,d)}}else if(d.active){if(d.ys.length>=4){const lo=Math.min(...d.ys),hi=Math.max(...d.ys),span=Math.max(.02,hi-lo);recordedPattern=d.ys.map(y=>clamp((y-lo)/span));pattern='custom';try{const s=JSON.parse(sessionStorage.getItem(VR_SESSION_KEY)||'{}');sessionStorage.setItem(VR_SESSION_KEY,JSON.stringify({...s,pattern:'custom',recordedPattern,cadence,updatedAt:Date.now()}))}catch{}pulse(src,.65,90);text('message','Controller pattern recorded · '+recordedPattern.length+' samples.')}vrDraw.set(src,{active:false,ys:[]})}}}
let program=null,posLoc=-1,mvpLoc=null,colorLoc=null,sizeLoc=null,buffer=null;
function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'shader');return s}
function initSpatial(){if(program||!gl)return;const vs=compile(gl.VERTEX_SHADER,'attribute vec3 a;uniform mat4 m;uniform float ps;void main(){gl_Position=m*vec4(a,1.0);gl_PointSize=ps;}'),fs=compile(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}');program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||'program');posLoc=gl.getAttribLocation(program,'a');mvpLoc=gl.getUniformLocation(program,'m');colorLoc=gl.getUniformLocation(program,'c');sizeLoc=gl.getUniformLocation(program,'ps');buffer=gl.createBuffer()}
function mul4(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v}return o}
function drawSet(mvp,verts,color,mode=gl.LINES,size=6){if(!verts.length)return;gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(posLoc);gl.vertexAttribPointer(posLoc,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(mvpLoc,false,mvp);gl.uniform4fv(colorLoc,color);gl.uniform1f(sizeLoc,size);gl.drawArrays(mode,0,verts.length/3)}
function sceneVertices(){const grid=[];for(let x=-4;x<=4;x+=.5)grid.push(x,0,-1,x,0,-8);for(let z=-1;z>=-8;z-=.5)grid.push(-4,0,z,4,0,z);const panel=[-1.15,.8,-2.5,1.15,.8,-2.5,1.15,.8,-2.5,1.15,2.15,-2.5,1.15,2.15,-2.5,-1.15,2.15,-2.5,-1.15,2.15,-2.5,-1.15,.8,-2.5,-.9,1.75,-2.49,.9,1.75,-2.49,-.9,1.5,-2.49,.9,1.5,-2.49,-.9,1.25,-2.49,.9,1.25,-2.49];return{grid,panel}}
const scene=sceneVertices();
function renderSpatial(frame,view){const mvp=mul4(view.projectionMatrix,view.transform.inverse.matrix);drawSet(mvp,scene.grid,[.18,.11,.25,1]);drawSet(mvp,scene.panel,[.63,.38,.86,1]);const f=(1-Math.cos(phase*Math.PI*2))/2*clamp(telemetry.depth),z=-1.45-f*1.15,y=1.18+Math.sin(phase*Math.PI*2)*.06;drawSet(mvp,[0,y,z],[.9,.72,1,1],gl.POINTS,14);const path=[0,1.18,-1.45,0,1.18,-2.6];drawSet(mvp,path,[.48,.28,.66,.9])}
function frame(t,frame){const dt=Math.min(80,t-lastT||16);lastT=t;const period=Math.max(420,3800-cadence*30),old=phase;phase=(phase+dt/period)%1;if(pattern==='custom'&&recordedPattern.length){const i=Math.min(recordedPattern.length-1,Math.floor(phase*recordedPattern.length));telemetry.depth=clamp(recordedPattern[i])}if(phase<old){const bias=directorBias();let amp=(.28+telemetry.intensity*.38)*hapticStrength*bias.hapticScale*stateHapticFactor();if(pattern==='pulse'&&Math.floor(t/period)%2)amp*=.42;else if(pattern==='wave')amp*=.62+.38*((Math.sin(t*.004)+1)/2);else if(pattern==='build')amp*=.5+.5*((t%8000)/8000);else if(pattern==='variable')amp*=.5+.5*((Math.sin(t*.007)+Math.sin(t*.0023)+2)/4);allPulse(amp,32+telemetry.depth*70)}updateInputs(t);controllerDraw(frame);if(xrSession){const pose=frame.getViewerPose(refSpace),layer=xrSession.renderState.baseLayer;gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);gl.enable(gl.DEPTH_TEST);gl.clearColor(.008,.004,.018,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(pose)for(const view of pose.views){const vp=layer.getViewport(view);gl.viewport(vp.x,vp.y,vp.width,vp.height);renderSpatial(frame,view)}xrSession.requestAnimationFrame(frame)}}
async function requestImmersive(){const root=$('xr-overlay');const opts={optionalFeatures:['local-floor','bounded-floor','hand-tracking','dom-overlay'],domOverlay:{root}};try{return await navigator.xr.requestSession('immersive-vr',opts)}catch(e){if(e?.name==='NotSupportedError'||e?.name==='TypeError')return navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor','hand-tracking']});throw e}}
async function enter(){if(xrSession)return;if(!window.isSecureContext){text('message','Immersive VR requires a secure HTTPS browser page.');return}if(!navigator.xr){text('message','WebXR is not available here. Open this page directly in Meta Quest Browser.');return}const enterButton=$('enter');if(enterButton){enterButton.disabled=true;enterButton.textContent='OPENING VR…'}try{const supported=await navigator.xr.isSessionSupported('immersive-vr');if(!supported)throw Error('This browser reports immersive-vr unsupported');if(!gl)throw Error('WebGL unavailable');text('message','Quest accepted the VR request · opening immersive session…');initSpatial();xrSession=await requestImmersive();await gl.makeXRCompatible();xrSession.updateRenderState({baseLayer:new XRWebGLLayer(xrSession,gl),depthNear:.05,depthFar:50});try{refSpace=await xrSession.requestReferenceSpace('local-floor')}catch{refSpace=await xrSession.requestReferenceSpace('local')}inputs.clear();for(const s of xrSession.inputSources)inputs.set(s,s);xrSession.addEventListener('inputsourceschange',e=>{for(const s of e.removed)inputs.delete(s);for(const s of e.added)inputs.set(s,s)});xrSession.addEventListener('end',()=>{xrSession=null;refSpace=null;inputs.clear();document.documentElement.classList.remove('xr-active');text('xr-status','VR READY');text('message','Immersive VR ended. You can re-enter or continue chatting here.');if($('exit'))$('exit').disabled=true;if($('enter')){$('enter').disabled=false;$('enter').textContent='ENTER IMMERSIVE VR'}});document.documentElement.classList.add('xr-active');text('xr-status','IMMERSIVE VR');text('message','Immersive stereo scene active. The violet marker follows the current depth pattern.');if($('exit'))$('exit').disabled=false;xrSession.requestAnimationFrame(frame)}catch(e){xrSession=null;document.documentElement.classList.remove('xr-active');text('message','VR start failed: '+String(e.message||e).slice(0,120));if(enterButton){enterButton.disabled=false;enterButton.textContent='ENTER IMMERSIVE VR'}}}
async function exit(){try{await xrSession?.end()}catch{}}
// ENTER / EXIT / CONTROLLER TEST are intentionally owned by vr-fallback.js in capture phase.
// This module handles chat, Director decisions, telemetry state and Autopilot only.
const sessionDialog=$('vr-session-dialog'),sessionForm=$('vr-session-form'),sessionSetup=$('session-setup');
function showSessionSetup(){try{sessionDialog?.showModal()}catch{}}
function paceFromCycle(s){const sec=Math.max(.7,Math.min(10,Number(s)||3));return clamp((5-sec)/4.3)}
function commitVrSession(){
  const entry=Math.max(.5,Math.min(10,Number($('vr-entry-speed')?.value)||3)),depth=Math.max(0,Math.min(100,Number($('vr-start-depth')?.value)||50))/100,cycle=Math.max(.7,Math.min(10,Number($('vr-stroke-speed')?.value)||3));
  telemetry={...telemetry,pace:paceFromCycle(cycle),depth,force:0,intensity:.2,entrySpeedS:entry,cycleTimeS:cycle,initialized:true,startedAt:Date.now()};cadence=Math.round(telemetry.pace*100);pattern='steady';try{window.NocturneSession?.initialize?.({entrySpeedS:entry,cycleTimeS:cycle,depth,force:0,intensity:.2,pattern:'steady',position,videoState:currentVideoState,embodied:embodiedState,visuals:visualPayload()},'vr-setup')}catch{}saveTelemetry();persistVisual();text('message','Session initialized · entry '+entry.toFixed(1)+'s · depth '+Math.round(depth*100)+'% · stroke '+cycle.toFixed(1)+'s. Enter VR when ready.');window.dispatchEvent(new CustomEvent('nocturne:vr-session-configured',{detail:{...telemetry,pattern,cadence,position,visuals:visualPayload()}}));return true;
}
sessionSetup?.addEventListener('click',showSessionSetup);
sessionForm?.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;if(!sessionForm.reportValidity()){e.preventDefault();return}commitVrSession()});
if(!telemetry.initialized)setTimeout(showSessionSetup,150);
function applyVrQuick(action){
  if(!telemetry.initialized){showSessionSetup();text('message','Initialize the session first.');return}
  if(action==='faster'){telemetry.cycleTimeS=Math.max(.7,telemetry.cycleTimeS-.3);telemetry.pace=paceFromCycle(telemetry.cycleTimeS)}
  else if(action==='slower'){telemetry.cycleTimeS=Math.min(10,telemetry.cycleTimeS+.3);telemetry.pace=paceFromCycle(telemetry.cycleTimeS)}
  else if(action==='deeper')telemetry.depth=clamp(telemetry.depth+.1);
  else if(action==='shallower')telemetry.depth=clamp(telemetry.depth-.1);
  else if(action==='ease')telemetry.intensity=clamp(telemetry.intensity-.1);
  else if(action==='force-up')telemetry.force=clamp(telemetry.force+.1);
  else if(action==='force-down')telemetry.force=clamp(telemetry.force-.1);
  else if(action==='energy-up')telemetry.intensity=clamp(telemetry.intensity+.1);
  else if(action==='energy-down')telemetry.intensity=clamp(telemetry.intensity-.1);
  saveTelemetry();syncHUD();text('message',action.toUpperCase()+' applied.');vrAiStatus('AI READY');
  if(autopilot)setTimeout(()=>autopilotTick(true),120);
}
window.addEventListener('nocturne:vr-ui-action',e=>{
  const action=String(e.detail?.action||'');
  if(action==='toggle-auto'){toggleAutopilot();return}
  if(action==='ai-choose'){autopilotTick(true);return}
  if(action==='chart-prev'){prevChart();return}
  if(action==='chart-next'){nextChart('manual');return}
  if(action==='user-peak'){registerUserPeak('vr-menu');return}
  if(action==='mic-chat'){startMicChat();return}
  if(action==='position-next'){position=POSITION_VALUES[(POSITION_VALUES.indexOf(position)+1)%POSITION_VALUES.length];saveTelemetry();persistVisual();rememberVr('position','Position changed to '+position+'.',['vr','position'],.25);text('message','Position · '+position.toUpperCase());return}
  if(action==='video-toggle'){visualCfg.videoEnabled=!visualCfg.videoEnabled;persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:currentVideoState,reason:'video-toggle',videoSound:visualCfg.videoSound}}));return}
  if(action==='video-sound'){visualCfg.videoSound=!visualCfg.videoSound;persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-video-sound',{detail:{enabled:visualCfg.videoSound}}));return}
  if(action==='voice-toggle'){visualCfg.voiceGuidance=!visualCfg.voiceGuidance;if(!visualCfg.voiceGuidance&&'speechSynthesis'in window)try{speechSynthesis.cancel()}catch{}persistVisual();return}
  if(action==='command-toggle'){visualCfg.commandMode=!visualCfg.commandMode;persistVisual();return}
  if(action==='pattern-next'){pattern=patternCore?.nextPattern?.(pattern)||'steady';saveTelemetry();syncHUD();rememberVr('pattern','Pattern changed to '+pattern+'.',['vr','pattern'],.28);return}
  if(action==='haptic-next'){hapticMode=patternCore?.nextHaptic?.(hapticMode)||'auto';saveTelemetry();syncHUD();return}
  if(action==='dynamic-toggle'){dynamicStrokes=!dynamicStrokes;saveTelemetry();syncHUD();rememberVr('pattern','Dynamic strokes '+(dynamicStrokes?'enabled':'disabled')+'.',['vr','pattern'],.22);return}
  if(action==='wave-size-next'){const vals=[.75,1,1.25,1.5,1.75];let i=vals.findIndex(v=>Math.abs(v-visualCfg.waveScale)<.02);visualCfg.waveScale=vals[(i<0?1:i+1)%vals.length];persistVisual();return}
  if(action==='wave-span-next'){const vals=[.65,.85,1,1.25,1.5,1.75];let i=vals.findIndex(v=>Math.abs(v-visualCfg.waveMotion)<.02);visualCfg.waveMotion=vals[(i<0?2:i+1)%vals.length];persistVisual();return}
  if(action==='tool-solid'){visualCfg.toolSolid=!visualCfg.toolSolid;persistVisual();return}
  if(action==='hold'){telemetry.startedAt=Date.now();saveTelemetry();chatState('done','Hold.');rememberVr('hold','User held the VR pattern on chart '+chartState.index+'.',['vr','hold'],.3);return}
  if(['faster','slower','deeper','shallower','ease','force-up','force-down','energy-up','energy-down'].includes(action))applyVrQuick(action);
});
const autoButton=$('vr-auto');
function syncAutoButton(){if(!autoButton)return;autoButton.setAttribute('aria-pressed',autopilot?'true':'false');autoButton.textContent=autopilot?'AUTOPILOT ON':'AUTOPILOT OFF';vrAiStatus(autopilot?'AI AUTO ON':'AI READY')}
function toggleAutopilot(){if(!telemetry.initialized){showSessionSetup();text('message','Initialize Entry Speed, Depth and Stroke Speed before Autopilot.');return false}autopilot=!autopilot;localStorage.setItem('nocturne.vr.autopilot.v1',autopilot?'on':'off');syncAutoButton();window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:currentVideoState,reason:'autopilot-toggle'}}));if(autopilot)autopilotTick(true);return true}
if(autoButton){autoButton.addEventListener('click',toggleAutopilot);syncAutoButton()}
function requireSessionControl(){if(telemetry.initialized)return true;showSessionSetup();text('message','Initialize Entry Speed, Depth and Stroke Speed first.');syncHUD();return false}
for(const [id,key]of[['vr-pace-range','pace'],['vr-depth-range','depth'],['vr-force-range','force'],['vr-energy-range','intensity']]){$(id)?.addEventListener('input',e=>{if(!requireSessionControl())return;telemetry[key]=clamp(Number(e.target.value)/100);if(key==='pace'){telemetry.cycleTimeS=Math.max(.7,Math.min(10,5-telemetry.pace*4.3));cadence=Math.round(telemetry.pace*100)}saveTelemetry();syncHUD()})}
$('vr-position')?.addEventListener('change',e=>{const v=String(e.target.value);if(POSITION_VALUES.includes(v)){position=v;saveTelemetry();persistVisual();text('message','Position · '+e.target.selectedOptions[0].textContent)}});
$('vr-video-toggle')?.addEventListener('click',()=>{visualCfg.videoEnabled=!visualCfg.videoEnabled;persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:currentVideoState,reason:'video-toggle',videoSound:visualCfg.videoSound}}))});
$('vr-video-sound')?.addEventListener('click',()=>{visualCfg.videoSound=!visualCfg.videoSound;persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-video-sound',{detail:{enabled:visualCfg.videoSound}}))});
$('vr-tool-solid')?.addEventListener('click',()=>{visualCfg.toolSolid=!visualCfg.toolSolid;persistVisual()});
$('vr-voice')?.addEventListener('click',()=>{visualCfg.voiceGuidance=!visualCfg.voiceGuidance;if(!visualCfg.voiceGuidance&&'speechSynthesis'in window)try{speechSynthesis.cancel()}catch{}persistVisual()});
$('vr-command-mode')?.addEventListener('click',()=>{visualCfg.commandMode=!visualCfg.commandMode;persistVisual()});
$('vr-pattern')?.addEventListener('change',e=>{const v=String(e.target.value);if(patternCore?.patterns?.includes(v)){pattern=v;saveTelemetry();syncHUD();rememberVr('pattern','Pattern set to '+pattern+'.',['vr','pattern'],.25)}});
$('vr-haptic-pattern')?.addEventListener('change',e=>{const v=String(e.target.value);if(patternCore?.hapticModes?.includes(v)){hapticMode=v;saveTelemetry();syncHUD()}});
$('vr-dynamic-strokes')?.addEventListener('click',()=>{dynamicStrokes=!dynamicStrokes;saveTelemetry();syncHUD()});
$('vr-chart-prev')?.addEventListener('click',prevChart);
$('vr-chart-next')?.addEventListener('click',()=>nextChart('browser'));
$('vr-user-peak')?.addEventListener('click',()=>registerUserPeak('browser'));
$('vr-wave-scale')?.addEventListener('input',e=>{visualCfg.waveScale=Math.max(.5,Math.min(2,Number(e.target.value)/100));persistVisual()});
$('vr-wave-motion')?.addEventListener('input',e=>{visualCfg.waveMotion=Math.max(.5,Math.min(1.8,Number(e.target.value)/100));persistVisual()});
function browserControlAction(id){
  if(id==='vr-auto')return toggleAutopilot();
  if(id==='vr-video-toggle'){visualCfg.videoEnabled=!visualCfg.videoEnabled;persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:currentVideoState,reason:'video-toggle',videoSound:visualCfg.videoSound}}));return true}
  if(id==='vr-video-sound'){visualCfg.videoSound=!visualCfg.videoSound;persistVisual();window.dispatchEvent(new CustomEvent('nocturne:vr-video-sound',{detail:{enabled:visualCfg.videoSound}}));return true}
  if(id==='vr-tool-solid'){visualCfg.toolSolid=!visualCfg.toolSolid;persistVisual();return true}
  if(id==='vr-voice'){visualCfg.voiceGuidance=!visualCfg.voiceGuidance;if(!visualCfg.voiceGuidance&&'speechSynthesis'in window)try{speechSynthesis.cancel()}catch{}persistVisual();return true}
  if(id==='vr-command-mode'){visualCfg.commandMode=!visualCfg.commandMode;persistVisual();return true}
  if(id==='vr-dynamic-strokes'){dynamicStrokes=!dynamicStrokes;saveTelemetry();syncHUD();return true}
  if(id==='vr-chart-prev'){prevChart();return true}
  if(id==='vr-chart-next'){nextChart('browser');return true}
  if(id==='vr-user-peak'){registerUserPeak('browser');return true}
  if(id==='vr-mic'||id==='vr-mic-chat'){startMicChat();return true}
  if(id==='vr-send'){sendChat();return true}
  return false;
}
const browserButtonIds=new Set(['vr-auto','vr-video-toggle','vr-video-sound','vr-tool-solid','vr-voice','vr-command-mode','vr-dynamic-strokes','vr-chart-prev','vr-chart-next','vr-user-peak','vr-mic','vr-mic-chat','vr-send']);
document.addEventListener('click',e=>{const b=e.target?.closest?.('button');if(!b||!browserButtonIds.has(b.id)||b.disabled)return;e.preventDefault();e.stopImmediatePropagation();browserControlAction(b.id)},true);
function controlAudit(){const ids=['vr-auto','vr-video-toggle','vr-video-sound','vr-tool-solid','vr-voice','vr-mic','vr-command-mode','vr-dynamic-strokes','vr-chart-prev','vr-user-peak','vr-chart-next','vr-send','vr-pattern','vr-haptic-pattern'],missing=ids.filter(id=>!$(id));return{ok:missing.length===0,total:ids.length,missing,patternCore:Boolean(patternCore),patterns:patternCore?.patterns?.length||0,haptics:patternCore?.hapticModes?.length||0}}
window.nocturneVrControlAudit=controlAudit;
persistVisual();
window.addEventListener('nocturne:vr-motion',e=>{vrMotion={...vrMotion,...(e.detail||{})};});
window.addEventListener('nocturne:vr-controller-state',e=>{vrControllers=Array.isArray(e.detail?.controllers)?e.detail.controllers.slice(0,4):[];});
window.addEventListener('nocturne:vr-tool-changed',e=>{const d=e.detail||{};rememberVr('tool','Selected tool '+String(d.name||d.id||'profile')+' · '+Math.round(Number(d.lengthMm)||0)+'×'+Math.round(Number(d.widthMm)||0)+'mm · travel '+Math.round(Number(d.travelMm)||0)+'mm.',['vr','tool'],.35);if(autopilot)setTimeout(()=>autopilotTick(true),100)});
window.addEventListener('nocturne:vr-cycle',e=>{vrMotion={...vrMotion,...(e.detail||{})};const cycle=Number(vrMotion.cycle)||0,now=Date.now();if(cycle>0&&cycle!==Number(chartState.lastCycle||0)){chartState.lastCycle=cycle;chartState.strokes+=Math.max(1,Number(patternCore?.strokeUnits?.(pattern))||1);if(chartState.strokes>=chartState.target){rememberVr('chart','Chart '+chartState.index+' reached '+chartState.target+' strokes.',['vr','chart'],.5);if(autopilot){saveChartState();setTimeout(()=>nextChart('stroke-target'),120)}else saveChartState()}else saveChartState()}if(autopilot&&vrImmersiveActive&&cycle!==lastCycleDecision&&cycle>0&&cycle%2===0&&now-lastCycleDecisionAt>5500){lastCycleDecision=cycle;lastCycleDecisionAt=now;setTimeout(()=>autopilotTick(true),80)}});
window.addEventListener('nocturne:vr-session',e=>{vrImmersiveActive=Boolean(e.detail?.active);loadVrSession();syncHUD();if(vrImmersiveActive&&autopilot)autopilotTick(true)});window.addEventListener('nocturne:vr-session-configured',()=>{loadVrSession();syncHUD()});
setInterval(()=>autopilotTick(false),20000);
refreshAvailableVideoStates().then(()=>{setVrVideoState(currentVideoState,'boot');setEmbodiedState(embodiedState,'boot')});
syncChartHUD();syncHUD();persistVisual();bootDirector();(async()=>{if(!navigator.xr){text('xr-status','WEBXR UNAVAILABLE');return}try{const ok=await navigator.xr.isSessionSupported('immersive-vr');text('xr-status',ok?'VR READY':'IMMERSIVE VR UNSUPPORTED');if(!ok)text('message','This browser reports that immersive-vr is unsupported. Open the page in Meta Quest Browser.')}catch{text('xr-status','XR CHECK FAILED')}})();
window.addEventListener('nocturne:suspend',()=>{if(!xrSession)return;try{allPulse(0,1)}catch{}});
window.__NOCTURNE_VR_MODULE_READY__=true;
