import{directorBias}from'./live-bridge.js';import{groundingContext}from'./anna-grounding.js';import{cloudManifest,stateById,baseStateId,familyCandidates}from'./video-state-core.js';
const $=id=>document.getElementById(id),clamp=v=>Math.max(0,Math.min(1,Number(v)||0)),canvas=$('xr-canvas');
// Quest immersive rendering is owned exclusively by vr-fallback.js. Do not reserve the XR canvas here.
const gl=null;
let xrSession=null,refSpace=null,inputs=new Map(),phase=0,lastT=0,lastPeak=0,token=sessionStorage.getItem('nocturne.staging.token');let vrImmersiveActive=false,autopilot=localStorage.getItem('nocturne.vr.autopilot.v1')==='on',autopilotBusy=false,currentVideoState=localStorage.getItem('nocturne.vr.video-state.v1')||'A01',availableVideoStates=[],vrMotion={phase:0,cycle:0,direction:'STILL',envelope:0},vrControllers=[],lastCycleDecision=-1,lastCycleDecisionAt=0;
const VR_SESSION_KEY='nocturne.vr.session.v070';
let telemetry={pace:0,depth:0,force:0,intensity:0,entrySpeedS:3,cycleTimeS:3,initialized:false,startedAt:0},pattern='steady',hapticStrength=.7,recordedPattern=[],cadence=0,vrDraw=new Map();
function loadVrSession(){try{const s=JSON.parse(sessionStorage.getItem(VR_SESSION_KEY)||'{}');if(!s.initialized){telemetry={...telemetry,pace:0,depth:0,force:0,intensity:0,initialized:false,startedAt:0};cadence=0;return false}telemetry={...telemetry,pace:clamp(s.pace),depth:clamp(s.depth),force:clamp(s.force),intensity:clamp(s.intensity),entrySpeedS:Math.max(.5,Math.min(10,Number(s.entrySpeedS)||3)),cycleTimeS:Math.max(.7,Math.min(10,Number(s.cycleTimeS)||3)),initialized:true,startedAt:Number(s.startedAt)||Date.now()};pattern=s.pattern||'steady';cadence=Math.max(0,Math.min(100,Number(s.cadence)||0));return true}catch{return false}}
loadVrSession();
function text(id,v){const e=$(id);if(e)e.textContent=v}
function syncHUD(){text('pace',telemetry.initialized?Math.round(telemetry.pace*100):0);text('depth',telemetry.initialized?Math.round(telemetry.depth*100):0);text('force',telemetry.initialized?Math.round(telemetry.force*100):0);text('energy',telemetry.initialized?Math.round(telemetry.intensity*100):0);text('diag-session',telemetry.initialized?'READY':'ZERO')}
async function bootDirector(){try{const r=await fetch('/v1/director/status',{headers:token?{'x-nocturne-session':token}:{}}),d=await r.json();if(d.sessionToken){token=d.sessionToken;sessionStorage.setItem('nocturne.staging.token',token)}vrAiStatus(d.openAIConfigured?'AI LIVE':'AI FALLBACK');return d}catch{vrAiStatus('AI OFFLINE');return null}}
function localJSON(key){try{return JSON.parse(localStorage.getItem(key)||'{}')}catch{return{}}}
function vrAiStatus(textValue){window.dispatchEvent(new CustomEvent('nocturne:vr-ai-status',{detail:{text:String(textValue||'AI READY')}}))}

async function refreshAvailableVideoStates(){try{const m=await cloudManifest();availableVideoStates=(m.states||[]).map(x=>x.id).filter(Boolean);text('diag-media',availableVideoStates.length?(availableVideoStates.length+' STATES'):'MISSING');return availableVideoStates}catch{text('diag-media','OFFLINE');return availableVideoStates}}
function chooseAvailableVideoState(id){id=String(id||'').toUpperCase();if(!stateById(id))id='A01';if(!availableVideoStates.length||availableVideoStates.includes(id))return id;const base=baseStateId(id),family=familyCandidates(base||id,[]).filter(x=>availableVideoStates.includes(x));return family[0]||(['A01','A02','A00'].find(x=>availableVideoStates.includes(x)))||id}
function setVrVideoState(id,reason='director'){const chosen=chooseAvailableVideoState(id);currentVideoState=chosen;try{localStorage.setItem('nocturne.vr.video-state.v1',chosen)}catch{}window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:chosen,reason}}));const el=$('vr-video-state');if(el)el.textContent=chosen;return chosen}
function saveTelemetry(){try{const s={...telemetry,pattern,cadence,updatedAt:Date.now()};sessionStorage.setItem(VR_SESSION_KEY,JSON.stringify(s));localStorage.setItem('nocturne.telemetry.v1',JSON.stringify({pace:telemetry.pace,depth:telemetry.depth,force:telemetry.force,intensity:telemetry.intensity,pattern,cadence,updatedAt:Date.now()}))}catch{}}
function applyDirector(q={},source='director'){
  const priorPace=telemetry.pace;const setNum=(key,target,delta)=>{if(Number.isFinite(target))telemetry[key]=clamp(target);else if(Number.isFinite(delta)&&delta)telemetry[key]=clamp(telemetry[key]+delta)};
  setNum('pace',q.paceTarget,q.paceDelta);setNum('depth',q.depthTarget,q.depthDelta);setNum('force',q.forceTarget,q.forceDelta);setNum('intensity',q.intensityTarget,q.intensityDelta);if(Math.abs(telemetry.pace-priorPace)>.0001)telemetry.cycleTimeS=Math.max(.7,Math.min(10,5-telemetry.pace*4.3));
  if(['steady','wave','pulse','build','variable','custom'].includes(q.pattern)&&q.pattern!=='keep')pattern=q.pattern;
  if(q.videoState&&q.videoState!=='keep')setVrVideoState(q.videoState,source);
  saveTelemetry();syncHUD();window.dispatchEvent(new CustomEvent('nocturne:vr-director-state',{detail:{source,videoState:currentVideoState,telemetry:{...telemetry},pattern,speech:String(q.speech||''),at:Date.now()}}));return q;
}
function directorContext(auto=autopilot){return{about:'Anna Sokolova is the Nocturne personal precision assistant inside immersive VR. Stay synchronized with the current physical simulation clock. Choose a coherent visual state from the available VR state list and keep telemetry changes grounded in the current cycle, direction and controller input. Available VR video states: '+availableVideoStates.join(', ')+'.',grounding:groundingContext(),psyche:localJSON('nocturne.anna.psyche.v056'),memory:localJSON('nocturne.anna.memory.v057'),experience:{...localJSON('nocturne.anna.experience.v061'),availableVideoStates},mode:'vr-live',motion:{...vrMotion},controllers:vrControllers,chart:{activePort:'V',lead:'AVATAR',pace:telemetry.pace,depth:telemetry.depth,force:telemetry.force,intensity:telemetry.intensity,rhythm:pattern,position:'keep',videoState:currentVideoState,autopilot:auto,entrySpeedS:telemetry.entrySpeedS,cycleTimeS:telemetry.cycleTimeS},recent:[]}}

function chatState(state,message){const line=$('vr-line'),button=$('vr-send');if(line){line.dataset.state=state;line.textContent=message}if(button){button.dataset.state=state;button.textContent=state==='sending'?'SENT':state==='thinking'?'…':'SEND'}}
async function sendChat(){const input=$('vr-message'),value=input?.value?.trim();if(!value)return;const button=$('vr-send');if(button)button.disabled=true;chatState('sending','Message received · sending to Anna…');vrAiStatus('AI RECEIVED');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),18000);try{if(!token)await bootDirector();chatState('thinking','Message received · Anna is thinking…');vrAiStatus('AI THINKING');const r=await fetch('/v1/director/respond',{method:'POST',signal:controller.signal,headers:{'content-type':'application/json','x-nocturne-session':token||''},body:JSON.stringify({text:value,context:directorContext(false)})}),d=await r.json();if(!r.ok)throw Error(d.error?.message||'Director unavailable');applyDirector(d.director||{},'chat');chatState('done',d.director?.speech||'I heard you.');vrAiStatus('AI APPLIED');if(input)input.value=''}catch(e){vrAiStatus('AI ERROR');chatState('error',e?.name==='AbortError'?'Anna did not answer within 18 seconds. Your message was received; try Send again.':'Chat error: '+String(e.message).slice(0,100))}finally{clearTimeout(timer);if(button)button.disabled=false;if(button)button.textContent='SEND'}}
$('vr-send')?.addEventListener('click',sendChat);$('vr-message')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();sendChat()}});
async function autopilotTick(force=false){if(!telemetry.initialized)return;if((!autopilot&&!force)||autopilotBusy||(!vrImmersiveActive&&!force))return;autopilotBusy=true;vrAiStatus('AI CHOOSING');try{if(!token)await bootDirector();if(!availableVideoStates.length)await refreshAvailableVideoStates();const r=await fetch('/v1/director/respond',{method:'POST',headers:{'content-type':'application/json','x-nocturne-session':token||''},body:JSON.stringify({text:'Continue the immersive VR experience in sync with the current motion cycle. Choose the most coherent available Anna visual state. Only adjust telemetry or pattern when the current cycle, direction, controller input and recent context support it. Keep speech brief and preserve continuity.',context:directorContext(true)})}),d=await r.json();if(r.ok){applyDirector(d.director||{},'autopilot');vrAiStatus('AI APPLIED');if(d.director?.speech&&d.director.speech.length<180)chatState('done',d.director.speech)}else vrAiStatus('AI ERROR')}catch{vrAiStatus('AI ERROR')}finally{autopilotBusy=false}}
async function pulse(src,s,d){const gp=src?.gamepad,acts=[];if(!gp)return false;if(gp.vibrationActuator)acts.push(gp.vibrationActuator);for(const a of gp.hapticActuators||[])acts.push(a);for(const a of acts){try{if(a.pulse)await a.pulse(clamp(s),d);else if(a.playEffect)await a.playEffect('dual-rumble',{duration:d,strongMagnitude:clamp(s),weakMagnitude:clamp(s*.6)})}catch{}}return acts.length>0}
const allPulse=(s,d)=>Promise.all([...inputs.values()].map(x=>pulse(x,s,d)));
async function peak(){await allPulse(1,95);setTimeout(()=>allPulse(.9,125),150);setTimeout(()=>allPulse(1,180),320)}
function updateInputs(t){for(const src of inputs.values()){const gp=src.gamepad,tr=gp?.buttons?.[0]?.value||0,gr=gp?.buttons?.[1]?.value||0,x=gp?.axes?.[2]??gp?.axes?.[0]??0,y=gp?.axes?.[3]??gp?.axes?.[1]??0,el=$(src.handedness+'-state');if(el)el.textContent='trigger '+tr.toFixed(2)+' · grip '+gr.toFixed(2)+' · stick '+x.toFixed(2)+','+y.toFixed(2);if(telemetry.initialized)telemetry.force=clamp(Math.max(telemetry.force*.94,tr,gr));if(telemetry.initialized&&tr>.92&&gr>.92&&t-lastPeak>2500){lastPeak=t;peak()}}syncHUD()}
function controllerDraw(frame){if(!refSpace)return;for(const src of inputs.values()){const gp=src.gamepad,gr=gp?.buttons?.[1]?.value||0,tr=gp?.buttons?.[0]?.value||0;let d=vrDraw.get(src)||{active:false,ys:[]};if(gr>.75&&tr<.25){const p=frame.getPose(src.targetRaySpace,refSpace);if(p){if(!d.active)d={active:true,ys:[]};d.ys.push(p.transform.position.y);if(d.ys.length>180)d.ys.shift();vrDraw.set(src,d)}}else if(d.active){if(d.ys.length>=4){const lo=Math.min(...d.ys),hi=Math.max(...d.ys),span=Math.max(.02,hi-lo);recordedPattern=d.ys.map(y=>clamp((y-lo)/span));pattern='custom';try{const s=JSON.parse(sessionStorage.getItem(VR_SESSION_KEY)||'{}');sessionStorage.setItem(VR_SESSION_KEY,JSON.stringify({...s,pattern:'custom',recordedPattern,cadence,updatedAt:Date.now()}))}catch{}pulse(src,.65,90);text('message','Controller pattern recorded · '+recordedPattern.length+' samples.')}vrDraw.set(src,{active:false,ys:[]})}}}
let program=null,posLoc=-1,mvpLoc=null,colorLoc=null,sizeLoc=null,buffer=null;
function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(s)||'shader');return s}
function initSpatial(){if(program||!gl)return;const vs=compile(gl.VERTEX_SHADER,'attribute vec3 a;uniform mat4 m;uniform float ps;void main(){gl_Position=m*vec4(a,1.0);gl_PointSize=ps;}'),fs=compile(gl.FRAGMENT_SHADER,'precision mediump float;uniform vec4 c;void main(){gl_FragColor=c;}');program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw Error(gl.getProgramInfoLog(program)||'program');posLoc=gl.getAttribLocation(program,'a');mvpLoc=gl.getUniformLocation(program,'m');colorLoc=gl.getUniformLocation(program,'c');sizeLoc=gl.getUniformLocation(program,'ps');buffer=gl.createBuffer()}
function mul4(a,b){const o=new Float32Array(16);for(let c=0;c<4;c++)for(let r=0;r<4;r++){let v=0;for(let k=0;k<4;k++)v+=a[k*4+r]*b[c*4+k];o[c*4+r]=v}return o}
function drawSet(mvp,verts,color,mode=gl.LINES,size=6){if(!verts.length)return;gl.useProgram(program);gl.bindBuffer(gl.ARRAY_BUFFER,buffer);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(verts),gl.DYNAMIC_DRAW);gl.enableVertexAttribArray(posLoc);gl.vertexAttribPointer(posLoc,3,gl.FLOAT,false,0,0);gl.uniformMatrix4fv(mvpLoc,false,mvp);gl.uniform4fv(colorLoc,color);gl.uniform1f(sizeLoc,size);gl.drawArrays(mode,0,verts.length/3)}
function sceneVertices(){const grid=[];for(let x=-4;x<=4;x+=.5)grid.push(x,0,-1,x,0,-8);for(let z=-1;z>=-8;z-=.5)grid.push(-4,0,z,4,0,z);const panel=[-1.15,.8,-2.5,1.15,.8,-2.5,1.15,.8,-2.5,1.15,2.15,-2.5,1.15,2.15,-2.5,-1.15,2.15,-2.5,-1.15,2.15,-2.5,-1.15,.8,-2.5,-.9,1.75,-2.49,.9,1.75,-2.49,-.9,1.5,-2.49,.9,1.5,-2.49,-.9,1.25,-2.49,.9,1.25,-2.49];return{grid,panel}}
const scene=sceneVertices();
function renderSpatial(frame,view){const mvp=mul4(view.projectionMatrix,view.transform.inverse.matrix);drawSet(mvp,scene.grid,[.18,.11,.25,1]);drawSet(mvp,scene.panel,[.63,.38,.86,1]);const f=(1-Math.cos(phase*Math.PI*2))/2*clamp(telemetry.depth),z=-1.45-f*1.15,y=1.18+Math.sin(phase*Math.PI*2)*.06;drawSet(mvp,[0,y,z],[.9,.72,1,1],gl.POINTS,14);const path=[0,1.18,-1.45,0,1.18,-2.6];drawSet(mvp,path,[.48,.28,.66,.9])}
function frame(t,frame){const dt=Math.min(80,t-lastT||16);lastT=t;const period=Math.max(420,3800-cadence*30),old=phase;phase=(phase+dt/period)%1;if(pattern==='custom'&&recordedPattern.length){const i=Math.min(recordedPattern.length-1,Math.floor(phase*recordedPattern.length));telemetry.depth=clamp(recordedPattern[i])}if(phase<old){const bias=directorBias();let amp=(.28+telemetry.intensity*.38)*hapticStrength*bias.hapticScale;if(pattern==='pulse'&&Math.floor(t/period)%2)amp*=.42;else if(pattern==='wave')amp*=.62+.38*((Math.sin(t*.004)+1)/2);else if(pattern==='build')amp*=.5+.5*((t%8000)/8000);else if(pattern==='variable')amp*=.5+.5*((Math.sin(t*.007)+Math.sin(t*.0023)+2)/4);allPulse(amp,32+telemetry.depth*70)}updateInputs(t);controllerDraw(frame);if(xrSession){const pose=frame.getViewerPose(refSpace),layer=xrSession.renderState.baseLayer;gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);gl.enable(gl.DEPTH_TEST);gl.clearColor(.008,.004,.018,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);if(pose)for(const view of pose.views){const vp=layer.getViewport(view);gl.viewport(vp.x,vp.y,vp.width,vp.height);renderSpatial(frame,view)}xrSession.requestAnimationFrame(frame)}}
async function requestImmersive(){const root=$('xr-overlay');const opts={optionalFeatures:['local-floor','bounded-floor','hand-tracking','dom-overlay'],domOverlay:{root}};try{return await navigator.xr.requestSession('immersive-vr',opts)}catch(e){if(e?.name==='NotSupportedError'||e?.name==='TypeError')return navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor','bounded-floor','hand-tracking']});throw e}}
async function enter(){if(xrSession)return;if(!window.isSecureContext){text('message','Immersive VR requires a secure HTTPS browser page.');return}if(!navigator.xr){text('message','WebXR is not available here. Open this page directly in Meta Quest Browser.');return}const enterButton=$('enter');if(enterButton){enterButton.disabled=true;enterButton.textContent='OPENING VR…'}try{const supported=await navigator.xr.isSessionSupported('immersive-vr');if(!supported)throw Error('This browser reports immersive-vr unsupported');if(!gl)throw Error('WebGL unavailable');text('message','Quest accepted the VR request · opening immersive session…');initSpatial();xrSession=await requestImmersive();await gl.makeXRCompatible();xrSession.updateRenderState({baseLayer:new XRWebGLLayer(xrSession,gl),depthNear:.05,depthFar:50});try{refSpace=await xrSession.requestReferenceSpace('local-floor')}catch{refSpace=await xrSession.requestReferenceSpace('local')}inputs.clear();for(const s of xrSession.inputSources)inputs.set(s,s);xrSession.addEventListener('inputsourceschange',e=>{for(const s of e.removed)inputs.delete(s);for(const s of e.added)inputs.set(s,s)});xrSession.addEventListener('end',()=>{xrSession=null;refSpace=null;inputs.clear();document.documentElement.classList.remove('xr-active');text('xr-status','VR READY');text('message','Immersive VR ended. You can re-enter or continue chatting here.');if($('exit'))$('exit').disabled=true;if($('enter')){$('enter').disabled=false;$('enter').textContent='ENTER IMMERSIVE VR'}});document.documentElement.classList.add('xr-active');text('xr-status','IMMERSIVE VR');text('message','Immersive stereo scene active. The violet marker follows the current depth pattern.');if($('exit'))$('exit').disabled=false;xrSession.requestAnimationFrame(frame)}catch(e){xrSession=null;document.documentElement.classList.remove('xr-active');text('message','VR start failed: '+String(e.message||e).slice(0,120));if(enterButton){enterButton.disabled=false;enterButton.textContent='ENTER IMMERSIVE VR'}}}
async function exit(){try{await xrSession?.end()}catch{}}
// ENTER / EXIT / CONTROLLER TEST are intentionally owned by vr-fallback.js in capture phase.
// This module handles chat, Director decisions, telemetry state and Autopilot only.
const sessionDialog=$('vr-session-dialog'),sessionForm=$('vr-session-form'),sessionSetup=$('session-setup');
function showSessionSetup(){try{sessionDialog?.showModal()}catch{}}
function paceFromCycle(s){const sec=Math.max(.7,Math.min(10,Number(s)||3));return clamp((5-sec)/4.3)}
function commitVrSession(){
  const entry=Math.max(.5,Math.min(10,Number($('vr-entry-speed')?.value)||3)),depth=Math.max(0,Math.min(100,Number($('vr-start-depth')?.value)||50))/100,cycle=Math.max(.7,Math.min(10,Number($('vr-stroke-speed')?.value)||3));
  telemetry={...telemetry,pace:paceFromCycle(cycle),depth,force:0,intensity:.2,entrySpeedS:entry,cycleTimeS:cycle,initialized:true,startedAt:Date.now()};cadence=Math.round(telemetry.pace*100);pattern='steady';saveTelemetry();syncHUD();text('message','Session initialized · entry '+entry.toFixed(1)+'s · depth '+Math.round(depth*100)+'% · stroke '+cycle.toFixed(1)+'s. Enter VR when ready.');window.dispatchEvent(new CustomEvent('nocturne:vr-session-configured',{detail:{...telemetry,pattern,cadence}}));return true;
}
sessionSetup?.addEventListener('click',showSessionSetup);
sessionForm?.addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;if(!sessionForm.reportValidity()){e.preventDefault();return}commitVrSession()});
if(!telemetry.initialized)setTimeout(showSessionSetup,150);
function applyVrQuick(action){
  if(!telemetry.initialized){showSessionSetup();text('message','Initialize the session first.');return}
  if(action==='faster'){telemetry.cycleTimeS=Math.max(.7,telemetry.cycleTimeS-.3);telemetry.pace=paceFromCycle(telemetry.cycleTimeS)}
  else if(action==='slower'){telemetry.cycleTimeS=Math.min(10,telemetry.cycleTimeS+.3);telemetry.pace=paceFromCycle(telemetry.cycleTimeS)}
  else if(action==='deeper')telemetry.depth=clamp(telemetry.depth+.1);
  else if(action==='ease')telemetry.intensity=clamp(telemetry.intensity-.1);
  saveTelemetry();syncHUD();text('message',action.toUpperCase()+' applied.');vrAiStatus('AI READY');
  if(autopilot)setTimeout(()=>autopilotTick(true),120);
}
window.addEventListener('nocturne:vr-ui-action',e=>{
  const action=String(e.detail?.action||'');
  if(action==='toggle-auto'){document.getElementById('vr-auto')?.click();return}
  if(action==='ai-choose'){autopilotTick(true);return}
  if(['faster','slower','deeper','ease'].includes(action))applyVrQuick(action);
});
const autoButton=$('vr-auto');function syncAutoButton(){if(!autoButton)return;autoButton.setAttribute('aria-pressed',autopilot?'true':'false');autoButton.textContent=autopilot?'AUTOPILOT ON':'AUTOPILOT OFF';vrAiStatus(autopilot?'AI AUTO ON':'AI READY')}if(autoButton){autoButton.addEventListener('click',()=>{if(!telemetry.initialized){showSessionSetup();text('message','Initialize Entry Speed, Depth and Stroke Speed before Autopilot.');return}autopilot=!autopilot;localStorage.setItem('nocturne.vr.autopilot.v1',autopilot?'on':'off');syncAutoButton();window.dispatchEvent(new CustomEvent('nocturne:vr-video-state',{detail:{id:currentVideoState,reason:'autopilot-toggle'}}));if(autopilot)autopilotTick(true)});syncAutoButton()}
window.addEventListener('nocturne:vr-motion',e=>{vrMotion={...vrMotion,...(e.detail||{})};});
window.addEventListener('nocturne:vr-controller-state',e=>{vrControllers=Array.isArray(e.detail?.controllers)?e.detail.controllers.slice(0,4):[];});
window.addEventListener('nocturne:vr-cycle',e=>{vrMotion={...vrMotion,...(e.detail||{})};const cycle=Number(vrMotion.cycle)||0,now=Date.now();if(autopilot&&vrImmersiveActive&&cycle!==lastCycleDecision&&cycle>0&&cycle%2===0&&now-lastCycleDecisionAt>5500){lastCycleDecision=cycle;lastCycleDecisionAt=now;setTimeout(()=>autopilotTick(true),80)}});
window.addEventListener('nocturne:vr-session',e=>{vrImmersiveActive=Boolean(e.detail?.active);loadVrSession();syncHUD();if(vrImmersiveActive&&autopilot)autopilotTick(true)});window.addEventListener('nocturne:vr-session-configured',()=>{loadVrSession();syncHUD()});
setInterval(()=>autopilotTick(false),20000);
refreshAvailableVideoStates().then(()=>setVrVideoState(currentVideoState,'boot'));
syncHUD();bootDirector();(async()=>{if(!navigator.xr){text('xr-status','WEBXR UNAVAILABLE');return}try{const ok=await navigator.xr.isSessionSupported('immersive-vr');text('xr-status',ok?'VR READY':'IMMERSIVE VR UNSUPPORTED');if(!ok)text('message','This browser reports that immersive-vr is unsupported. Open the page in Meta Quest Browser.')}catch{text('xr-status','XR CHECK FAILED')}})();
window.addEventListener('nocturne:suspend',()=>{if(!xrSession)return;try{allPulse(0,1)}catch{}});