import {WORLD_VERSION,WORLD_KEY,ROOMS,LOOKS,LABELS,TABS,normalizeWorld,parse,createCharacter,canCreateCharacter,applyLooks,newRecipe,ownedClips,normalizeRay,panelHit,hitButton,textureMemory} from './world-core.js';
import {RoomRenderer,MeshBuilder,mul,pose,inverse,perspective,identity,floorTexture} from './world-graphics.js';
import {buildRoom} from './world-rooms.js';
import {paintPanel,htmlPanel,PANEL_W,PANEL_H} from './world-panel.js';
import {readBlob,writeBlob,checksum,inspectVideo,downloadBlob} from './player-storage.js';
import {chooseClip,clipMeta,inspectStorage} from './reliability-core.js';
import {bounded,waitFor} from './player-deck.js';
const $=id=>document.getElementById(id),canvas=$('room');
let renderer,world,store,avatars,media,about,active=null,session=null,reference=null,viewerMatrix=pose(0,1.62,2.5),yaw=0,pitch=0,panelEnabled=false,menuVisible=true,lastSceneTime=0,transition=0,transitionAction=null,activeClip=null,videoUrl=null,videoEpoch=0,playing=false,hover=null,buttons=[],modal=null,notice='',raf=0,lastFrame=0,frameCount=0,fpsStart=0,paused=false,screenVisible=false,resetOrigin=null,controllerAim=[],clipPage=0,lookPage=0,recipePage=0;
const uiCanvas=document.createElement('canvas'),video=$('world-video');let videoTextureReady=false;
const panel={x:-.85,y:1.62,z:.66,yaw:.12,width:1.18,height:1.30,pixelsW:PANEL_W,pixelsH:PANEL_H};
const videoPanel={x:1.1,y:1.55,z:.30,yaw:-.20,width:1.75,height:.985};
let panelData,roomInfo,latestWorldRaw=null;
function report(text){notice=text;$('system-status').textContent=text;refresh();}
function persist(){const raw=localStorage.getItem(WORLD_KEY);if(raw!==latestWorldRaw)throw Error('Spatial settings changed in another tab. Reload before saving.');const next=JSON.stringify(world);localStorage.setItem(WORLD_KEY,next);latestWorldRaw=next;}
function readCurrent(){const state=inspectStorage(localStorage);if(!state.ok)throw Error('Saved workspace state needs recovery. Open the main workspace; do not clear browser data.');store=state.values;avatars=store.avatars.length?store.avatars:store.avatar?[store.avatar]:[];media=store.media;about=store.about||{};active=avatars.find(a=>a.id===active?.id)||avatars.find(a=>a.id===store.avatar?.id)||avatars[0]||null;}
function updateAvatar(next){const list=parse(localStorage.getItem('aurelia.preview.avatars')||'[]');const idx=list.findIndex(a=>a.id===next.id);if(idx<0)throw Error('Character no longer available. Reload the workspace.');list[idx]=next;localStorage.setItem('aurelia.preview.avatars',JSON.stringify(list));if(active?.id===next.id)localStorage.setItem('aurelia.preview.avatar',JSON.stringify(next));readCurrent();}
const b=(id,label,extra={})=>({id,label,...extra}),row=(...items)=>({type:'row',items}),note=text=>({type:'note',text});
function characterDraft(){return active?{...world.draft,name:active.name,age:active.age,looks:active.looks||world.draft.looks}:world.draft;}
function model(){const nav=[row(...['Rooms','Character','Looks'].map(t=>b('tab:'+t,t,{selected:world.tab===t}))),row(...['Loops','About You','Settings'].map(t=>b('tab:'+t,t,{selected:world.tab===t})))];let title=world.tab,subtitle='SPATIAL / '+WORLD_VERSION,controls=[];
 if(modal?.type==='keyboard'){
  const letters=['QWERTYUIOP','ASDFGHJKL','ZXCVBNM'];title=modal.label;subtitle='Use the controller keyboard or type on your computer.';controls=[note(((modal.value||'').length>150?'…':'')+(modal.value||'').slice(-150)+'▌')];for(const line of letters)controls.push(row(...[...line].map(c=>b('key:'+c,c))));controls.push(row(b('key:SPACE','Space'),b('key:DELETE','⌫'),b('key:CASE',modal.lower?'abc':'ABC')));controls.push(row(b('key:CANCEL','Cancel'),b('key:SAVE','Save',{primary:true})));return{title,subtitle,controls,notice:'Personal edits stay in this browser. No speech recording is active.'};
 }
 if(modal?.type==='select'){title=modal.label;subtitle='Select one · same choices in VR and on your phone';const start=(modal.page||0)*7;controls=[row(b('modal-close','← Back')),...modal.values.slice(start,start+7).map((v,i)=>b('option:'+(start+i),String(v),{selected:modal.current===v})),...(modal.values.length>7?[row(b('options-prev','Previous',{disabled:start===0}),b('options-next','More',{disabled:start+7>=modal.values.length}))]:[])];return{title,subtitle,controls,notice};}
 if(modal?.type==='confirm'){return{title:modal.label,subtitle:'Review before continuing',controls:[note(modal.text),row(b('modal-close','Cancel'),b('confirm','Confirm',{primary:true}))],notice};}
 if(world.tab==='Rooms'){
  title='Your rooms.';subtitle='Modelled in 3D · no panoramic background';controls=[...ROOMS.map(r=>b('scene:'+r.id,r.name+' / '+r.kind,{selected:world.scene===r.id})),row(b('light:day','Daylight',{selected:world.mood==='day'}),b('light:dusk','Dusk',{selected:world.mood==='dusk'})),b('view:recenter','Recenter workspace'),row(b('turn:left','Look left'),b('turn:right','Look right')),note('Room controls and character tools stay inside the immersive session. Grip / squeeze brings the panel back in front.')];
 }else if(world.tab==='Character'){
  title=active?active.name:'Create your character.';subtitle='Free plan / one character included';controls=[b('name','Name: '+(active?.name||world.draft.name||'Choose a name')),b('age','Adult age: '+(active?.age||world.draft.age)),b('tab:Looks','Choose appearance & personality →'),b(active?'save-character':'create-character',active?'Save character changes':'Create free character',{primary:true,disabled:!active&&!canCreateCharacter(avatars)}),...(avatars.length>1?[b('switch-character','Switch legacy beta character'),note('Existing beta characters are retained. New free accounts receive one character. No extra-character checkout is enabled.')]:[note('Appearance controls save design instructions. A generated likeness appears only after an authorized generation job.')])];
 }else if(world.tab==='Looks'){
  title='Designed, not guessed.';subtitle=active?'Appearance for '+active.name:'Appearance for your first character';const keys=Object.keys(LOOKS).filter(k=>k!=='age'),looks=active?.looks||world.draft.looks;
  controls=[...keys.slice(lookPage*5,lookPage*5+5).map(k=>b('look:'+k,LABELS[k]+': '+(looks[k]||LOOKS[k][0]))),row(b('looks-prev','Previous',{disabled:lookPage===0}),b('looks-next','More choices',{disabled:(lookPage+1)*5>=keys.length})),note('Select a field to open its multiple-choice list. No image is generated just by changing a trait.')];
 }else if(world.tab==='Loops'){
  title='Performance library.';subtitle=active?active.name+' / local approved media':'Create a character first';const owned=ownedClips(media,active?.id),recipe=world.recipe;
  controls=[row(b('play','▶ Play',{primary:true}),b('pause','Pause'),b('next','Next variant')),b('loop-state','State: '+recipe.state.replaceAll('_',' ')),row(b('loop-frame',recipe.frame+' view'),b('loop-pose',recipe.pose+' pose')),row(b('loop-duration',recipe.duration+' seconds'),b('loop-variants',recipe.variants+' variants')),b('save-recipe','Save generation setup',{disabled:!active}),row(b('recipes','Saved setups ('+world.recipes.filter(r=>r.avatarId===active?.id).length+')'),b('clips','Saved clips ('+owned.length+')')),...(activeClip&&activeClip.player?.reviewed!==true?[b('approve-clip','Review / approve current clip')]:[]),note('Saved setups are drafts, not paid jobs. Live Venice generation is not connected on this staging host.')];
 }else if(world.tab==='About You'){
  title='Your context.';subtitle='Private account profile / same device workspace';controls=[b('about:preferredName','Name: '+(about.preferredName||'Not set')),b('about:bio','About me: '+(about.bio?about.bio.slice(0,28)+'…':'Add a note')),b('about:interests','Interests: '+(about.interests||'Add interests').slice(0,33)),b('about:goals','Goals: '+(about.goals||'Add goals').slice(0,33)),b('about:communicationStyle','Communication style'),b('profile-sharing','Profile marked for future AI: '+(about.shareWithAI===true?'On':'Off')),note('No profile or photo is sent to a model here. Use the keyboard to edit without leaving immersive VR.')];
 }else{
  title='Make it feel right.';subtitle='Comfort, graphics and continuity';controls=[b('quality','Material resolution: '+world.quality+' × '+world.quality),b('motion','Reduced transitions: '+(world.settings.reduceMotion?'On':'Off')),b('panel-recenter','Bring controls in front'),b('save-world','Save room & loop settings'),b('import-video','Import clip / system file picker'),b('diagnostics','Export private-data-free diagnostics'),b(session?'exit-vr':'enter-vr',session?'Exit immersive VR':'Enter immersive VR',{primary:true}),note('4K uses one 4096² procedural surface map (~'+textureMemory(4096)+' MB with mipmaps). Headset rendering resolution is separate. Import/export may require exiting VR for system dialogs.')];
 }
 return{title,subtitle,controls:[...nav,...controls],notice:notice||'Device-local · One free character · No live AI / model generation'};
}
function refresh(){if(!world||!renderer)return;const m=model();htmlPanel($('controls'),m,dispatch);buttons=paintPanel(uiCanvas,{...m,hover});renderer.texture(1,uiCanvas);$('tabs').replaceChildren();for(const tab of TABS){const x=document.createElement('button');x.textContent=tab;x.className=world.tab===tab?'selected':'';x.onclick=()=>dispatch('tab:'+tab);$('tabs').append(x);}const room=ROOMS.find(r=>r.id===world.scene);$('room-kind').textContent=room.kind.toUpperCase();$('room-title').textContent=room.name+'.';$('room-subtitle').textContent=room.subtitle;$('quality-label').textContent=(world.quality/1024)+'K surface · '+textureMemory(world.quality)+' MB texture';}
function popup(key,label,values,current){modal={type:'select',key,label,values,current};refresh();}
function editText(key,label,value){modal={type:'keyboard',key,label,value:String(value||''),lower:false};refresh();}
async function dispatch(id){try{
 if(id.startsWith('tab:')){world.tab=id.slice(4);modal=null;persist();refresh();return;}
 if(id==='modal-close'){modal=null;refresh();return;}
 if(id==='options-prev'||id==='options-next'){if(modal?.type==='select'){modal.page=Math.max(0,(modal.page||0)+(id==='options-next'?1:-1));refresh();}return;}
 if(id.startsWith('option:')){const {key,values}=modal,value=values[Number(id.slice(7))];modal=null;await choose(key,value);return;}
 if(id.startsWith('key:')){if(!modal||modal.type!=='keyboard')return;const k=id.slice(4);if(k==='CANCEL')modal=null;else if(k==='CASE')modal.lower=!modal.lower;else if(k==='DELETE')modal.value=modal.value.slice(0,-1);else if(k==='SPACE'&&modal.value.length<(modal.key==='name'?40:2500))modal.value+=' ';else if(k==='SAVE'){const {key,value}=modal;modal=null;await choose(key,value);}else if(modal.value.length<(modal.key==='name'?40:2500))modal.value+=modal.lower?k.toLowerCase():k;refresh();return;}
 if(id==='confirm'){const fn=modal.run;modal=null;await fn();return;}
 if(id.startsWith('scene:')){changeScene(id.slice(6));return;}
 if(id.startsWith('light:')){world.mood=id.slice(6);persist();refresh();return;}
 if(id.startsWith('turn:')){turn(id==='turn:left'?Math.PI/6:-Math.PI/6);return;}
 if(['view:recenter','panel-recenter'].includes(id)){recenter();return;}
 if(id==='name'){editText('name','Character name',active?.name||world.draft.name);return;}
 if(id==='age'){popup('age','Choose adult age',LOOKS.age,active?.age||world.draft.age);return;}
 if(id.startsWith('look:')){const k=id.slice(5);popup('look:'+k,LABELS[k],LOOKS[k],active?.looks?.[k]||world.draft.looks[k]);return;}
 if(id==='looks-prev'||id==='looks-next'){lookPage=id==='looks-prev'?Math.max(0,lookPage-1):lookPage+1;refresh();return;}
 if(id==='create-character'){
  readCurrent();const made=createCharacter(avatars,world.draft,'avatar_'+crypto.randomUUID());const existing=parse(localStorage.getItem('aurelia.preview.avatars')||'[]');if(existing.length)throw Error('One character is included. Reload to use your existing character.');localStorage.setItem('aurelia.preview.avatars',JSON.stringify([made]));localStorage.setItem('aurelia.preview.avatar',JSON.stringify(made));active=made;readCurrent();report('Character saved. Appearance is design data; no likeness has been generated.');return;
 }
 if(id==='save-character'){persist();report('Character appearance and design choices are saved.');return;}
 if(id==='switch-character'){modal={type:'select',key:'active',label:'Existing beta characters',values:avatars.map((a,i)=>(i+1)+'. '+a.name),current:avatars.findIndex(a=>a.id===active?.id)+1+'. '+active?.name};refresh();return;}
 if(id.startsWith('about:')){const key=id.slice(6);editText('about:'+key,key==='bio'?'About me':key,about[key]||'');return;}
 if(id==='profile-sharing'){modal={type:'confirm',label:'Profile sharing preference',text:'This only marks text for future authorized AI use. It does not upload profile content or enable photo sharing.',run:async()=>{about={...about,shareWithAI:about.shareWithAI!==true};localStorage.setItem('aurelia.preview.about',JSON.stringify(about));report('Profile sharing preference saved. No model request was made.');}};refresh();return;}
 if(id==='loop-state'){popup('recipe:state','Performance state',['idle_neutral','listen_engaged','speak_calm','think_reflective','react_pleased'],world.recipe.state);return;}
 if(id==='loop-frame'){popup('recipe:frame','Footage framing',['portrait','full-body','wide'],world.recipe.frame);return;}
 if(id==='loop-pose'){popup('recipe:pose','Pose group',['center','seated','standing'],world.recipe.pose);return;}
 if(id==='loop-duration'){popup('recipe:duration','Target duration',[5,10],world.recipe.duration);return;}
 if(id==='loop-variants'){popup('recipe:variants','Variant count',[1,3,5],world.recipe.variants);return;}
 if(id==='save-recipe'){const r=newRecipe(active?.id,world,'recipe_'+crypto.randomUUID());world.recipes.push(r);world.recipes=world.recipes.slice(-40);persist();report('Generation setup saved as a draft. It has NOT been submitted or charged.');return;}
 if(id==='recipes'){const list=world.recipes.filter(r=>r.avatarId===active?.id);modal={type:'select',key:'recipe-load',label:'Saved generation drafts',values:list.map((r,i)=>`${i+1}. ${r.state} / ${r.frame} / ${r.duration}s`),current:null};refresh();return;}
 if(id==='clips'){const list=ownedClips(media,active?.id);modal={type:'select',key:'clip',label:'Saved clips · review before play',values:list.map((c,i)=>(i+1)+'. '+(c.name||c.id)),current:null};refresh();return;}
 if(id==='quality'){popup('quality','Surface texture size',[1024,2048,4096],world.quality);return;}
 if(id==='motion'){world.settings.reduceMotion=!world.settings.reduceMotion;persist();refresh();return;}
 if(id==='save-world'){persist();report('Room, traits and generation drafts saved on this browser.');return;}
 if(id==='approve-clip'&&activeClip){modal={type:'confirm',label:'Approve this local clip?',text:'Confirm you watched this clip, its framing and loop transition are suitable, and you own it or have permission to use it. This is human review, not automated content verification.',run:async()=>{readCurrent();const clip=media.find(c=>c.id===activeClip.id&&c.avatarId===active.id);if(!clip)throw Error('Clip is no longer available.');clip.player={...clip.player,reviewed:true,rightsConfirmedAt:new Date().toISOString()};localStorage.setItem('aurelia.preview.media',JSON.stringify(media));report('Clip marked reviewed for this character.');}};refresh();return;}
 if(id==='play'||id==='next'){await playClip(id==='next');return;}
 if(id==='pause'){pause();report('Playback paused.');return;}
 if(id==='enter-vr'){await enterVR();return;}
 if(id==='exit-vr'){await session?.end();return;}
 if(id==='import-video'){if(session){report('Exiting immersive mode for the browser file picker. Return through Enter VR after importing.');await session.end();}$('world-import').click();return;}
 if(id==='diagnostics'){if(session)await session.end();const gl=renderer.gl;downloadBlob(new Blob([JSON.stringify({version:WORLD_VERSION,scene:world.scene,quality:world.quality,viewport:[canvas.width,canvas.height],maxTextureSize:gl.getParameter(gl.MAX_TEXTURE_SIZE),roomTriangles:roomInfo.mesh.length/36,accountSync:false,ai:false,physicalHeadsetVerified:false},null,2)],{type:'application/json'}),'AURELIA-SPATIAL-DIAGNOSTICS.json');report('Diagnostics exported without personal profile or media contents.');return;}
 }catch(error){report(error.message||'Action could not finish. Your data was not cleared.');}}
async function choose(key,value){if(key==='name'){if(active){const name=String(value).trim();if(!name)throw Error('Enter a name.');updateAvatar({...active,name:name.slice(0,40)});}else world.draft.name=String(value).slice(0,40);}
 else if(key==='age'){if(active)updateAvatar({...active,age:Number(value)});else world.draft.age=Number(value);}
 else if(key.startsWith('look:')){const k=key.slice(5);if(active)updateAvatar(applyLooks(active,{...active.looks,[k]:value}));else world.draft.looks[k]=value;}
 else if(key.startsWith('about:')){about={...about,[key.slice(6)]:String(value).slice(0,2500)};localStorage.setItem('aurelia.preview.about',JSON.stringify(about));}
 else if(key.startsWith('recipe:'))world.recipe[key.slice(7)]=value;
 else if(key==='quality'){if(value>renderer.gl.getParameter(renderer.gl.MAX_TEXTURE_SIZE))throw Error('This device does not support that texture size.');if(session)throw Error('Change graphics quality before entering VR to avoid a headset frame stall.');world.quality=value;renderer.texture(0,floorTexture(world.quality,world.scene==='bathroom'),true);}
 else if(key==='active'){pause();active=avatars[Number(String(value).split('.')[0])-1]||active;activeClip=null;recent=[];screenVisible=false;video.removeAttribute('src');video.load();if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=null;localStorage.setItem('aurelia.preview.avatar',JSON.stringify(active));}
 else if(key==='recipe-load'){const n=Number(String(value).split('.')[0])-1,r=world.recipes.filter(r=>r.avatarId===active?.id)[n];if(r){world.recipe={state:r.state,frame:r.frame,pose:r.pose,duration:r.duration,variants:r.variants};world.tab='Loops';notice='Saved generation draft loaded. No job was submitted.';}}
 else if(key==='clip'){const c=ownedClips(media,active?.id)[Number(String(value).split('.')[0])-1];if(c){if(c.player?.reviewed!==true){modal={type:'confirm',label:'Review before playback',text:'This clip is not approved for automatic use. Preview it once now; then return to Loops to approve it explicitly. Nothing will be uploaded.',run:async()=>{await playExact(c,true);}};}else{world.recipe={...world.recipe,state:clipMeta(c).state,frame:clipMeta(c).frame,pose:clipMeta(c).startPose};await playExact(c);}}}
 persist();refresh();}
let videoAbort=null;
function pause(){videoEpoch++;videoAbort?.abort();video.pause();playing=false;}
let recent=[];
async function playClip(next=false){readCurrent();if(!active)throw Error('Create or select a character first.');if(!next&&activeClip?.avatarId===active.id&&activeClip.player?.reviewed===true&&clipMeta(activeClip).state===world.recipe.state&&clipMeta(activeClip).frame===world.recipe.frame&&clipMeta(activeClip).startPose===world.recipe.pose&&video.src&&video.paused){await bounded(video.play(),null,12000);playing=true;report('Playing saved media. No generation request.');return;}
 const picked=chooseClip(media,{avatarId:active.id,state:world.recipe.state,frame:world.recipe.frame,pose:world.recipe.pose,recent});if(!picked.clip)throw Error('No reviewed clip matches these settings. Import and review a clip first.');await playExact(media.find(c=>c.id===picked.clip.id));}
async function playExact(clip,previewOnly=false){if(!clip||clip.avatarId!==active?.id)throw Error('Clip does not belong to the selected character.');pause();const id=++videoEpoch,owner=active.id,blob=await readBlob(clip.id);if(id!==videoEpoch||owner!==active?.id)return;if(!blob)throw Error('The video file is not stored in this browser. Import or reattach it in the Loop Deck.');
 const controller=new AbortController();videoAbort=controller;const url=URL.createObjectURL(blob);if(videoUrl)URL.revokeObjectURL(videoUrl);videoUrl=url;videoTextureReady=false;screenVisible=false;
 try{const ready=waitFor(video,'loadeddata',controller.signal,12000);video.src=url;video.loop=clip.family!=='transition';video.load();await ready;await bounded(video.play(),controller.signal,12000);if(id!==videoEpoch||owner!==active?.id){video.pause();return;}activeClip=clip;recent=[clip.id,...recent.filter(i=>i!==clip.id)].slice(0,8);screenVisible=true;playing=true;report(previewOnly?'Review preview only. Use Approve current clip after watching.':'Playing a saved local clip. Video is flat footage inside a 3D room.');}
 catch(error){video.pause();if(id===videoEpoch){screenVisible=false;video.removeAttribute('src');video.load();URL.revokeObjectURL(url);videoUrl=null;}throw error;}finally{if(videoAbort===controller)videoAbort=null;}}

function changeScene(id){if(world.scene===id)return;pause();lastSceneTime=performance.now();transition=1;transitionAction=()=>{world.scene=id;roomInfo=buildRoom(id);renderer.mesh('room',roomInfo.mesh);renderer.texture(0,floorTexture(world.quality,id==='bathroom'),true);persist();refresh();};if(world.settings.reduceMotion){transitionAction();transitionAction=null;transition=0;}else refresh();}
function panelMeshes(){const u=new MeshBuilder();u.panel(panel);renderer.mesh('panel',u.result());const v=new MeshBuilder();v.panel(videoPanel,0xffffff,6);renderer.mesh('screen',v.result());}
function recenter(){const m=viewerMatrix,x=m[12],y=m[13],z=m[14],a=Math.atan2(m[8],m[10]);panel.yaw=a;panel.x=x-Math.sin(a)*1.45-Math.cos(a)*.75;panel.z=z-Math.cos(a)*1.45+Math.sin(a)*.75;panel.y=y;videoPanel.yaw=a;videoPanel.x=x-Math.sin(a)*2.1+Math.cos(a)*1.0;videoPanel.z=z-Math.cos(a)*2.1-Math.sin(a)*1.0;videoPanel.y=y;panelMeshes();panelEnabled=true;refresh();}
function turn(amount){if(session){resetOrigin={yaw:amount};}else yaw+=amount;}
async function enterVR(){if(session)return;try{if(!navigator.xr)throw Error('This browser does not expose WebXR. Use the headset browser or desktop room preview.');const s=await navigator.xr.requestSession('immersive-vr',{optionalFeatures:['local-floor']});session=s;const gl=renderer.gl;await gl.makeXRCompatible();s.updateRenderState({baseLayer:new XRWebGLLayer(s,gl,{alpha:false,framebufferScaleFactor:1})});try{reference=await s.requestReferenceSpace('local-floor');}catch{reference=await s.requestReferenceSpace('local');reference=reference.getOffsetReferenceSpace(new XRRigidTransform({x:0,y:-1.62,z:0}));}
 reference=reference.getOffsetReferenceSpace(new XRRigidTransform({x:0,y:0,z:-2.5}));document.body.classList.add('in-vr');panelEnabled=true;let positioned=false;
 s.addEventListener('select',event=>{const p=event.frame.getPose(event.inputSource.targetRaySpace,reference);if(!p)return;const hit=hitButton(buttons,panelHit(normalizeRay(p.transform.matrix),panel));if(hit)dispatch(hit.id);});
 s.addEventListener('squeeze',()=>recenter());
 s.addEventListener('end',()=>{session=null;reference=null;pause();document.body.classList.remove('in-vr');panelEnabled=false;renderer.gl.bindFramebuffer(renderer.gl.FRAMEBUFFER,null);resetOrigin=null;report('Immersive session ended. Settings saved; playback paused.');requestAnimationFrame(tick);});
 s.addEventListener('visibilitychange',()=>{if(s.visibilityState!=='visible')pause();});
 cancelAnimationFrame(raf);
 const draw=(time,frame)=>{if(session!==s)return;s.requestAnimationFrame(draw);if(resetOrigin){const a=resetOrigin.yaw;reference=reference.getOffsetReferenceSpace(new XRRigidTransform({x:0,y:0,z:0},{x:0,y:Math.sin(a/2),z:0,w:Math.cos(a/2)}));resetOrigin=null;}
  const vp=frame.getViewerPose(reference);if(!vp)return;viewerMatrix=vp.transform.matrix;if(!positioned){recenter();positioned=true;}
  controllerAim=[];let nextHover=null;
  for(const source of s.inputSources){const p=frame.getPose(source.targetRaySpace,reference);if(!p)continue;const ray=normalizeRay(p.transform.matrix),hit=panelHit(ray,panel),button=hitButton(buttons,hit);if(button)nextHover=button.id;const length=hit?hit.t:1.4;controllerAim.push({ray,length,hit:!!hit});}
  if(hover!==nextHover){hover=nextHover;refresh();}drawRays();update(time);const layer=s.renderState.baseLayer;gl.bindFramebuffer(gl.FRAMEBUFFER,layer.framebuffer);gl.clearColor(.025,.024,.032,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);
  for(const view of vp.views){const port=layer.getViewport(view);gl.viewport(port.x,port.y,port.width,port.height);render(mul(view.projectionMatrix,view.transform.inverse.matrix),[view.transform.position.x,view.transform.position.y,view.transform.position.z]);}
 };s.requestAnimationFrame(draw);report('Immersive mode: point and trigger to select; squeeze / grip to recenter menus.');
 }catch(error){if(session)await session.end().catch(()=>{});session=null;document.body.classList.remove('in-vr');throw error;}}
function drawRays(){const bld=new MeshBuilder();for(const {ray,length,hit} of controllerAim){const end=ray.origin.map((v,i)=>v+ray.direction[i]*length);bld.ellipsoid(...end,.007,.007,.007,hit?0xd6b4ff:0xbfc9d4,7,0,8,6);for(let i=0;i<12;i++){const t=i/12*length;const p=ray.origin.map((v,j)=>v+ray.direction[j]*t);bld.ellipsoid(...p,.0015,.0015,.0015,0x907ca5,7,0,4,3);}}renderer.mesh('rays',bld.result());}
function update(time){if(transitionAction&&time-lastSceneTime>160){transitionAction();transitionAction=null;lastSceneTime=time;}transition=world.settings.reduceMotion?0:transitionAction?Math.min(1,(time-lastSceneTime)/160):Math.max(0,1-(time-lastSceneTime)/280);if(time-lastSceneTime>300&&!transitionAction)transition=0;
 if(video.readyState>=2&&screenVisible){try{renderer.texture(2,video);videoTextureReady=true;}catch{pause();screenVisible=false;report('Video texture upload failed; playback stopped.');}}
 frameCount++;if(time-fpsStart>1000){$('fps').textContent=Math.round(frameCount*1000/(time-fpsStart))+' fps';fpsStart=time;frameCount=0;}}
function render(vp,eye){renderer.draw(vp,eye,{day:world.mood==='day'?1:0,fade:Math.min(.97,transition),videoAspect:video.videoWidth/video.videoHeight||16/9,screenAspect:videoPanel.width/videoPanel.height,targets:['room',...(panelEnabled?['panel','rays']:[]),...(screenVisible&&videoTextureReady?['screen']:[])]});}
function desktopMatrix(){const m=pose(0,1.62,2.50,yaw),p=identity();p[5]=Math.cos(pitch);p[6]=Math.sin(pitch);p[9]=-Math.sin(pitch);p[10]=Math.cos(pitch);return mul(m,p);}
function tick(time){if(session||paused)return;raf=requestAnimationFrame(tick);const dpr=Math.min(devicePixelRatio||1,1.6),w=Math.round(innerWidth*dpr),h=Math.round(innerHeight*dpr);if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}
 const gl=renderer.gl;gl.bindFramebuffer(gl.FRAMEBUFFER,null);gl.viewport(0,0,w,h);gl.clearColor(.025,.024,.032,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);viewerMatrix=desktopMatrix();update(time);render(mul(perspective(Math.PI/2.85,w/h),inverse(viewerMatrix)),[viewerMatrix[12],viewerMatrix[13],viewerMatrix[14]]);}
function onScreenRay(x,y){const aspect=innerWidth/innerHeight,tan=Math.tan(Math.PI/2.85/2),dx=(x/innerWidth*2-1)*tan*aspect,dy=(1-y/innerHeight*2)*tan;const n=Math.hypot(dx,dy,1),m=desktopMatrix();return{origin:[m[12],m[13],m[14]],direction:[(m[0]*dx+m[4]*dy-m[8])/n,(m[1]*dx+m[5]*dy-m[9])/n,(m[2]*dx+m[6]*dy-m[10])/n]};}
function bind(){
 $('vr').onclick=()=>enterVR().catch(e=>report(e.message));$('recenter').onclick=()=>{if(!session){yaw=0;pitch=0;}recenter();};$('toggle-menu').onclick=()=>{menuVisible=!menuVisible;$('control-shell').classList.toggle('hidden',!menuVisible);$('toggle-menu').textContent=menuVisible?'Hide controls':'Show controls';};
 let down=null;canvas.onpointerdown=e=>{down={x:e.clientX,y:e.clientY,yaw,pitch};canvas.setPointerCapture(e.pointerId);};canvas.onpointermove=e=>{if(down){yaw=down.yaw-(e.clientX-down.x)*.003;pitch=Math.max(-.9,Math.min(.9,down.pitch-(e.clientY-down.y)*.003));}};canvas.onpointerup=e=>{if(down&&Math.hypot(e.clientX-down.x,e.clientY-down.y)<6&&panelEnabled){const hit=hitButton(buttons,panelHit(onScreenRay(e.clientX,e.clientY),panel));if(hit)dispatch(hit.id);}down=null;};
 window.addEventListener('keydown',e=>{if(modal?.type==='keyboard'){if(e.key==='Backspace'){e.preventDefault();dispatch('key:DELETE');}else if(e.key==='Enter')dispatch('key:SAVE');else if(e.key.length===1&&modal.value.length<(modal.key==='name'?40:2500)){modal.value+=e.key;refresh();}return;}if(e.key==='Escape'){modal=null;refresh();}if(e.key.toLowerCase()==='m'){panelEnabled=!panelEnabled;refresh();}});
 $('world-import').onchange=async()=>{const file=$('world-import').files?.[0];$('world-import').value='';if(!file)return;if(!active)return report('Create a character before importing footage.');try{const owner=active.id,meta=await inspectVideo(file),hash=await checksum(file),id='media_'+crypto.randomUUID();readCurrent();if(active?.id!==owner)throw Error('Character changed during import. Try again.');if(media.some(c=>c.avatarId===owner&&c.sha256===hash))throw Error('That exact clip is already saved for this character.');await writeBlob(id,file);const record={id,avatarId:owner,name:file.name,bytes:file.size,sha256:hash,state:world.recipe.state,family:'performance',...meta,player:{...meta,frame:world.recipe.frame,startPose:world.recipe.pose,endPose:world.recipe.pose,reviewed:false}};try{localStorage.setItem('aurelia.preview.media',JSON.stringify([...media,record]));}catch{throw Error('Media metadata could not be saved; preserve your existing backup.');}readCurrent();report('Clip saved locally, awaiting review. Use the Loop Deck to approve it for automatic playback.');}catch(e){report(e.message);}};
 document.addEventListener('visibilitychange',()=>{if(document.hidden){pause();if(!session){paused=true;cancelAnimationFrame(raf);}}else if(!session){paused=false;requestAnimationFrame(tick);}});
 window.addEventListener('pagehide',()=>{pause();session?.end();if(videoUrl)URL.revokeObjectURL(videoUrl);cancelAnimationFrame(raf);renderer.dispose();});canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();pause();cancelAnimationFrame(raf);session?.end();$('fatal').hidden=false;$('fatal-message').textContent='Graphics context was lost. Reload the page; your saved rooms and characters were not cleared.';});window.addEventListener('storage',e=>{if(e.key===WORLD_KEY)report('Spatial settings changed in another tab. Reload before saving to avoid overwriting them.');});
}
async function boot(){try{readCurrent();latestWorldRaw=localStorage.getItem(WORLD_KEY);world=normalizeWorld(latestWorldRaw?parse(latestWorldRaw):{});renderer=new RoomRenderer(canvas);world.quality=Math.min(world.quality,renderer.gl.getParameter(renderer.gl.MAX_TEXTURE_SIZE));roomInfo=buildRoom(world.scene);renderer.mesh('room',roomInfo.mesh);panelMeshes();renderer.texture(0,floorTexture(world.quality,world.scene==='bathroom'),true);lastSceneTime=-1000;bind();refresh();$('system-status').textContent='3D rooms ready · device-local · live AI not connected';requestAnimationFrame(tick);
 const support=!!(navigator.xr&&await navigator.xr.isSessionSupported('immersive-vr').catch(()=>false));$('vr').disabled=!support;$('vr').textContent=support?'Enter immersive VR':'Desktop / phone preview';globalThis.AureliaWorld={version:WORLD_VERSION,dispatch,world,renderer,model,roomInfo,get panels(){return{panel,buttons};},get session(){return session;}};
 }catch(e){$('fatal').hidden=false;$('fatal-message').textContent=e.message;$('system-status').textContent='Startup stopped without clearing saved data.';}}
boot();
